### ISSUE TITLE
robot-simulator: "turning edge cases" are not necessarily edge cases

### ISSUE THREAD

**Issue by petertseng** [exercism/xhaskell#116]
We have:

```haskell
  [ testCase "turning edge cases" $ do
    North @=? turnRight West
    West @=? turnLeft North
-- other tests omitted
   ]
```

These aren't necessarily edge cases. It's only an edge case for *the particular implementation* used in the example solution, where North is the first variant of the `data Bearing =`, and West is the last. Any student may have chosen a different ordering, at which point these aren't edge cases anymore.

**Comment by rbasso** [comment]
You are right!

What do you think we should do? Chance the `TestLabel`? Add more tests?

**Comment by petertseng** [comment]
I currently favor testing all eight cases in the product of (north, east, south, west) x (left, right). I think that makes the most sense, unless there are compelling reasons not to test them all.

**Comment by rbasso** [comment]
Considering there is no `/x-common/robot-simulator.json`, I don't see anything  preventing that.
