### ISSUE TITLE
check-exercises.hs redundant import warning after GHC 7.10.x

### ISSUE THREAD

**Issue by petertseng** [exercism/xhaskell#122]
Travis keeps warning with:

```
_test/check-exercises.hs:18:1: warning: [-Wunused-imports]
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
```

Should check whether that's required. If not required, remove the line completely. If required, add the `()`.

**Comment by rbasso** [comment]
This warning is cause by *Prelude* exporting some functions from `Control.Applicative` from GHC version 7.10.x.

If we remove this line,`check-exercises.hs` it will not compile  in older versions:

```
    Not in scope: `<$>'
    Perhaps you meant `</>' (imported from System.FilePath)
```

[Functor-Applicative-Monad Proposal](https://wiki.haskell.org/Functor-Applicative-Monad_Proposal)
[GHC 7.10.x Migration Guide](https://ghc.haskell.org/trac/ghc/wiki/Migration/7.10#GHCsaysTheimportof...isredundant)

The last link has some solution to avoid this warning.
