### ISSUE TITLE
Warning "Defined but not used: `testCase`" when compiling some test modules.

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#145]
Some exercises show a warning when compiling the test module:

```
Defined but not used: `testCase`
```

This can confuse users and is not considered good practice.

Unused code:

- function `testCase`
- import of `Assertion`

Affected exercises:

- atbash-cipher
- binary
- crypto-square
- hexadecimal
- largest-series-product
- nth-prime
- prime-factors
- raindrops
- roman-numerals
- scrabble-score
- triangle

**Proposed solution**: remove the unused code.

**Comment by kytrinyx** [comment]
Thanks, @rbasso I would support removing unused code.
