### ISSUE TITLE
Learning Haskell suggestion

### ISSUE THREAD

**Issue by jasonkuhrt** [exercism/xhaskell#148]
It should mention http://haskellbook.com I think, especially if only one book is going to be listed.

**Comment by rbasso** [comment]
I tried to take a look at it, but it's not a free resource, right?

Learn You a Haskell is free and very good at introducing the the language. Maybe it's major problem is the lack of exercises.

Another options would be Real World Haskell, that's a more task oriented. But I think it's not very updated, and conceptually it's weaker than LYAH.

**Comment by jasonkuhrt** [comment]
Understood regarding price but the quality difference between LYAH and HPFP is stark. [I am impressed](https://twitter.com/JasonKuhrt/status/698674829659107333) with the book (on page ~900 of 1200).

**Comment by rbasso** [comment]
Nice to know that *Haskell Programming from First Principles* it's that good.

Anyway, you should join us and start solving or even writing new exercises here at https://exercism.io . People are friendly and it is a nice experience. At least that is my beginner's opinion.

**Comment by rbasso** [comment]
Considering it's not clear at the moment if we should list zero, one or more books, free or paid book, in `LEARNING.md`, I'm closing this issue, postponing this discussion until someone proposes a complete rewrite of it.

If anyone is against it, I'll reopen it immediately.

**Comment by petertseng** [comment]
Does this mean that it would be useful to have a discussion in general about how much and what kind of resources one would put in LEARNING.md? I note that https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#track-anatomy has a few notes but not to that level of detail. Should there be?

I know I often think "let's favor listing more, and we'll let the students make the choice", but this can have the negative effect of making the student think "you recommend too many things, now each of your recommendations individually carries less weight; how can I know which resources are the most important"? So it may be good to know what others think about it.

**Comment by rbasso** [comment]
I'm just a *freshman* here, and this is the only *track* I use, so I really have no idea.

The person who can probably give you an answer is @kytrinyx . She certainly has a clearer vision than us about that. Sorry to bother you Katrina! :grin:

**Comment by kytrinyx** [comment]
> Sorry to bother you Katrina! 

It's never a bother!

> Does this mean that it would be useful to have a discussion in general about how much and what kind of resources one would put in LEARNING.md? 

Yeah, that would be a good discussion to have. My first instinct is that it's fine to list both, but we should make it clear when we're recommending a paid resource.

> "you recommend too many things [...]"

Agreed, we should be parsimonious. One thing we could do, though, is to give some guidelines about when you would want to try a paid resource.

> Understood regarding price but the quality difference between LYAH and HPFP is stark. I am impressed with HPFP (on page ~900 of 1200). I read LYAH twice without it being enough to successfully transition me into Haskell, but HPFP is doing just that, finally!

This is really good information. I know it's a personal experience, but this is the sort of thing that I think it would be helpful to say something about.
