### ISSUE TITLE
discussion: Tracking dependencies (update README.md to include package "lens").

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#151]
I was tracking the [dependencies](https://github.com/exercism/xhaskell/files/319495/dependencies.txt) for each of the exercises and example solutions - to run some local experiments with compartmentalized tests - and I found a minor omission in `README.md`.

The table below summarizes all dependencies, except for the package `base`:

| package | all | exercises | check-exercises | README | bootstrap | GHC |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| array | x | x | | | | x |
| attoparsec | x | x | | x | x | |
| containers | x | x | | | | x |
| directory | x | | x | | | x |
| filepath | x | | x | | | x |
| HUnit | x | x | | x | x | |
| lens | x | x | | | x | |
| parallel | x | x | | x | x | |
| process | x | | x | | | x |
| QuickCheck | x | x | | x | x | |
| random | x | x | | x | x | |
| split | x | x | | x | x | |
| stm | x | x | | x | x | |
| text | x | x | | x | x | |
| time | x | x | | | | x |
| unix | x | | x | | | x |
| vector | x | x | | x | x | |

I opened this issue not because the package `lens` isn't listed in `README.md`, but to ask a question:

**Should we keep a more detailed track of dependencies?**

The advantages would be:

- Automatically generate correct lists of dependencies.
- Allow *sandboxed*, automated tests with Cabal, Stack or Nix.
- Optionally, deliver exercises as automatically generated projects.

I'm not proposing any of those thing! (I'm already happy doing it locally)
I'm also not proposing any specific form of dependency track. This we can discuss later, if enough people think it's a good idea.

What I would like to know is if anyone has anything in favor of against keeping some form of updated track of each exercise's dependencies inside `xhaskell`.

So... anyone?

**Comment by petertseng** [comment]
I think I would like to see such a thing, partially for curiosity's sake. Maybe it can help us answer the question "Wow, we really hate having a dependency on X, what exercises do we have to change in order to be able to drop the dependency?" - not that I have a specific value of X, but just hypothetically (and other questions of that nature)

I guess if I had to think of counterargument it would be "how do we make sure the lists actually stay up to date?" but this is in a way dependent on the actual implementation and of course is quite possible in many.

**Comment by rbasso** [comment]
The only "practical" way to **enforce** correct dependencies declaration is to use a sand-boxed environment to test the exercises in *Travis*. This way it would not be possible to miss a dependency, but I believe it would still be possible to declare unneeded packages.

**Comment by rbasso** [comment]
> I think I would like to see such a thing, partially for curiosity's sake. Maybe it can help us answer the question "Wow, we really hate having a dependency on X...

Fell free to try it! :smile: 

> I guess if I had to think of counterargument it would be "how do we make sure the lists actually stay up to date?"

I'm finishing solving this problem too, but that would be another PR that depends on this one...

**Comment by rbasso** [comment]
Found another missing dependency: `old-locale`

There is conditional compilation in `gigasecond`, so when it is compiled with GHC < 7.10, it depends on it.

The updated dependencies are already in #159.
