### ISSUE TITLE
nucleotide-count: Change types to return an Either.

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#157]
We are considering changing the interface of the problem `nucleotide-count`. The idea (#115)  is to allow a more idiomatic solution to this problem, returning a *Maybe*, an *Either* or something else, instead of forcing the user to throw an `error` with the specific message: **invalid nucleotide 'X'**.

It could be something like this:

```haskell
module DNA (count, nucleotideCounts) where

count :: Char -> String -> Maybe Int
nucleotideCounts :: String -> Maybe (Map Char Int)
```

This is just and sketch, and it can/should change. It depends only on the feedback here!

Any suggestion or comment is welcome! :smile:

**Comment by abo64** [comment]
+1 for not not throwing any unforced errors in Haskell.
But if you change the signature I would rather go for an `Either String (Map Char Int)`.
This way you also stay closer to the original exercise.

**Comment by rbasso** [comment]
In this case, what would `Left String` contain? An error message, the input *String* or just the invalid characters?

**Comment by abo64** [comment]
Definitely the error message. I think this is also how most people use `Either` for error handling.

**Comment by rbasso** [comment]
We don't need specify that. For the tests it probably would be enough to check if it is a `Left`.

**Comment by abo64** [comment]
fine with me.

**Comment by petertseng** [comment]
I'm assuming that if we'll have `nucleotideCounts :: String -> Either String (Map Char Int)` then we would also have `count :: Char -> String -> Either String Int`.

That seems reasonable to me (the initial suggestions of just the `Maybe` seem fine as well). Agreed that there's no need to test for a specific error message, just that it's `Left`.

**Comment by samjonester** [comment]
I agree with @abo64 that the original error string should be the `Left`. It feels like it would be an extremely message if I was to use these methods IRL.

**Comment by rbasso** [comment]
If anyone is willing to write a PR, I would gladly review/merge it. :smile:

Anyone?
