### ISSUE TITLE
phone-number: Change types to return Maybe.

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#158]
We are considering changing the interface of the problem `phone-number`. The idea (#115)  is to allow a more idiomatic solution to this problem, returning a *Maybe*, an *Either* or something else, instead of signalling invalid input with the *String* **00000000**

It could be something like this:

```haskell
module Phone (areaCode, number, prettyPrint) where

areaCode    :: String -> Maybe String
number      :: String -> Maybe String
prettyPrint :: String -> Maybe String
```

This is just and sketch, and it can/should change. It depends only on the feedback here!

Any suggestion or comment is welcome! :smile:

**Comment by abo64** [comment]
a `Maybe String` would be perfect here. I was thinking the same when I did this exercise.

**Comment by rbasso** [comment]
I already wrote a solution but I'm waiting for #159 to open the PR, because I changed a dependency that's already listed there. So I'm assigning it to myself to avoid duplicated work.

**Comment by samjonester** [comment]
Oops! Didn't see your comment @rbasso. Feel free to merge or decline my pr (https://github.com/exercism/xhaskell/pull/163) at your discretion.

**Comment by rbasso** [comment]
You already did it, so I'll merge yours. :smile:
