### ISSUE TITLE
rna-transcription: Change return type to Maybe

### ISSUE THREAD

**Issue by samjonester** [exercism/xhaskell#166]
This exercise doesn't define a test case for "non dna" characters, so many people are throwing errors for invalid input unnecessarily. It seems like that solution has gone viral, and since it's early in the haskell track could influence people to throw errors instead of using the safer type of `Maybe`. Thoughts on making this change?

**Comment by samjonester** [comment]
The exercise, for reference. http://exercism.io/exercises/haskell/rna-transcription/readme

**Comment by kytrinyx** [comment]
This sounds like a good move to me. That would align with other changes we've been making, per https://github.com/exercism/xhaskell/issues/115

**Comment by rbasso** [comment]
:+1:  for that!

We could even supply a stub `DNA.hs` as we do *forth*, *list-ops* and *zipper*, so people will not have to infer the signature.
