### ISSUE TITLE
rna-transcription: Is the new version with Maybe too hard to be at the start of the track?

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#191]
After #168 (#166), I think that `rna-transcription` may be out of place.

To solve it, the user needs to work with a list of Maybes, but beginners don't seem to understand `sequence` and `traverse` easily.

A good starter exercise with `Maybe` would be great, but I think that `rna-transcription` demands more advanced knowledge.

I propose to move it further in the track as soon as possible, to avoid loosing new users stuck at the *third exercise*.

**Comment by rbasso** [comment]
What do you think about it, @samjonester ?

**Comment by rbasso** [comment]
I would love to hear your opinion on this one @petertseng!

**Comment by rbasso** [comment]
Is `rna-transcrption` in a good position in the track or should we move it?

What do you think about it, @samjonester ?
I would love to hear your opinion on this one @petertseng!

*I already asked 6 users what they think about the new version but I still don't have the answers.*

**Comment by samjonester** [comment]
That sounds like a good idea. It's not as difficult as phone number or nucleotide count, so I think it should come before them. Alternatively, it could be moved to be by hamming / space age.

**Comment by samjonester** [comment]
Also, learning about mapM, foldlM, bind, ... we're big lightbulb moments for me while learning Haskell.

**Comment by rbasso** [comment]
Ok. I'll move it between `hamming` and `space-age`.
With #193 it's position will probably change, but we don't know when we will do that.

**Comment by petertseng** [comment]
As a final note:

> A good starter exercise with `Maybe` would be great

What if we used `hamming` for the purpose? Note that it's only defined for equal-length strings. and https://github.com/exercism/x-common/blob/master/hamming.json says to test unequal length strings and expect an error, which could be a good time to use `Maybe`.

**Comment by rbasso** [comment]
> What if we used hamming for the purpose?

Perfect, @petertseng. `hamming` should definitely return a `Maybe`. :smile: 

I'll add both to the list in #194 so we don't forget about it.
