### ISSUE TITLE
Making the Haskell track more gradual

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#193]
###### Making the Haskell track more gradual
Anyone would like to take the humongous task of solving at least part of this?

1. Check what knowledge is needed to solve each of the exercises.
2. Reorder the exercises creating the most gradual progression possible.
3. Change and move some exercises to make it even more gradual.

If we did this at least for the first 20 exercises it would be nice. If we did this for the entire track it would be fantastic.

**Comment by rbasso** [comment]
Comment from a user about `robot-name`: 

> This exercise was brutal! :)
>
> I found the jump in difficulty from the last exercise to this one to be quite severe!

**Comment by petertseng** [comment]
I went through and tried to write down a few notes for each exercise. Each line has the exercise name, a space, then a list of notes. I could not be exhaustive, and for some exercise I was too lazy to figure out what to write so I only wrote "?"

Stars mean I think the exercise is quite involved.

I don't know how useful this list will be. It is likely it will be need to be improved and completed. I would say big things to pay attention to are the problem that use the IO monad, and stuff I marked with stars.

```
accumulate reimplement library, recursion, test enforces non-strict
allergies bitwise
all-your-base Maybe, math
anagram filter, String manipulate
atbash-cipher String manipulate
bank-account IO monad
beer-song repetitive String generation
binary we should deprecate soon, math
binary-search-tree make a data structure, recursion
bob String manipulate
clock math
connect searching, **
crypto-square String manipulate
custom-set make a data structure
difference-of-squares math
etl combine library functions
food-chain repetitive String generation
forth parser, **
gigasecond math, time
go-counting partition grid, **
grade-school make a data structure (kinda)
grains math, Maybe
hamming simultaneous iteration, Maybe
hexadecimal we should deprecate soon, math
house repetitive String generation
kindergarten-garden ?
largest-series-product ?
leap math
lens-person lens, if you just use the library maybe it's easy, maybe interesting learning about the types if you implement yourself, *
linked-list make a data structure, IO monad
list-ops make a data structure
luhn ?
matrix ?
meetup date manipulation
minesweeper count grid, *
nth-prime math, filter
nucleotide-count Either
ocr-numbers ?
octal we should deprecate soon, math
palindrome-products ?
parallel-letter-frequency parallel
pascals-triangle ?
phone-number Maybe
pig-latin String manipulate
pov searching, *
prime-factors math
pythagorean-triplet math
queen-attack ?
raindrops math
rna-transcription Maybe
robot-name IO monad, random
robot-simulator ?
roman-numerals ?
saddle-points ?
say ?
scrabble-score ?
secret-handshake typeclass to make it work with both Int and String seems tricky
series
sgf-parsing parser
sieve ?
simple-cipher String manipulate
simple-linked-list make a data structure
space-age math
strain reimplement library, recursion, test enforces non-strict
sublist reimplement library
sum-of-multiples math, filter
triangle math
trinary we should deprecate soon, math
word-count ?
wordy parser
zipper make a data structure, *
```

**Comment by rbasso** [comment]
Thank you very much, @petertseng! :+1: 

I'll be forced to take another at each of the problems to rewrite test suites to *fail-fast* with `rspec`. It will be a good opportunity to complement your work. :smile:

**Comment by kytrinyx** [comment]
Also check out the blog post by @IanWhitney
http://designisrefactoring.com/2016/07/09/exercism-shouldnt-make-you-cry/

**Comment by rbasso** [comment]
Great post! Thanks!

**Comment by rbasso** [comment]
With the new `config.yaml` format (#274), there is no need to discuss categorization of the exercises here anymore. After that, reordering the exercises will not be so hard.

Considering that this issue is dead for more almost two months, I will close it so e can focus on what needs to be done now! #274 

I anyone opposes, I'll immediately reopen it.
