### ISSUE TITLE
Should strain test non-strict evaluation, like accumulate does?

### ISSUE THREAD

**Issue by petertseng** [exercism/xhaskell#208]
We can make this part of #194.

Note that the [accumulate tests](https://github.com/exercism/xhaskell/blob/master/exercises/accumulate/test/Tests.hs) have a test that make sure that the accumulate function is non-strict. That was added in https://github.com/exercism/xhaskell/commit/d238a331c2bccaa1d86522198e0a85235a6356d6

Is this a goal of the track that we promote non-strict evaluation when appropriate? And if so, do we want to add a similar test to [strain](https://github.com/exercism/xhaskell/blob/master/exercises/strain/test/Tests.hs)?

They might look something like this:

```haskell
  , testCase "keep non-strict" $ do
    let ws = "yes" : error "no"
    ["yes"] @=? take 1 (keep (const True) ws)
  , testCase "discard non-strict" $ do
    let ws = "yes" : error "no"
    ["yes"] @=? take 1 (discard (const False) ws)
```

Would want a more descriptive message than "no", of course.

**Comment by petertseng** [comment]
Actually, maybe I misunderstand, I can't get an implementation to fail these new tests.

**Comment by petertseng** [comment]
The difference is that the function `const False` doesn't cause its argument to be evaluated. However, if the test uses `(\x -> seq x False)` (or as hlint suggests ```(`seq` False)```) then non-strict solutions could fail. I will amend my proposal.

**Comment by petertseng** [comment]
Proposal changed:

v2 proposal had this:

```haskell
let ws = ["yes", "yup", error "nope", error "no"]
["yes", "yup"] @=? take 2 (keep (`seq` True) ws) 
```

v3 proposal has this:

```haskell
let ws = "yes" : error "no"
["yes"] @=? take 1 (keep (const True) ws)
```

`seq` is no longer necessary, even more non-strictness is enforced.

v2 proposal allows a CPS solution, v3 doesn't.

Losing CPS solutions is unfortunate, but I'm not sure anyone is complaining. We can go back to v2 proposal if anyone really wants to keep CPS solutions in the running. v2 solution still rejects the solutions in [earlier comment](https://github.com/exercism/xhaskell/issues/208#issuecomment-233240989).

**Comment by rbasso** [comment]
1. In `accumulate`, I don't think we need that check, because it's the second exercise in the track, and it's too much to ask for a complete newbie. But it's already there, and I don't think too many people get that wrong.

2. In `strain`, I think that it makes sense to enforce a lazy implementation. `v3` is simple enough to allow the user to understand why it failed the test. Also, I would avoid exposing users to `seq` unless it's really needed.
```
