### ISSUE TITLE
gigasecond: Completely rewrite the exercise or deprecate it.

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#230]
The way it is now, `gigasecond` has some problems:

- It is too easy and boring.
- All answers are almost the same: `fromDay = addUTCTime 1e9`
- Does not match `exercism/x-common/gigasecond.json`.

Seems that, at least in other tracks, it can be interesting: https://github.com/exercism/xhaskell/issues/192#issuecomment-234806673

> In the Go track gigasecond is a fantastic exercise. People tackle it in so many different ways, and there are myriad opportunities to talk about idioms in the language and certain language features.
>
> I think that if it can be turned into a more interesting exercise, then that's worth doing. If not, just deprecate it.

**Edit:** This exercise was changed in branch `hspec-fail-fast`. Please use that branch for any PR related to it or wait until it's merged in `master`.

**Comment by kytrinyx** [comment]
I'm totally OK with deprecating it if it's too boring and we can't come up with a more interesting variant.

**Comment by rbasso** [comment]
Until now, there is no proposal about how to make `gigasecond` an interesting exercise, so I think it's best to deprecate it now. If anyone finds a way to make it a good exercise in Haskell, we can easily *undeprecate* it.
