### ISSUE TITLE
[all-your-base, leap, hamming] tests are swapped

### ISSUE THREAD

**Issue by NobbZ** [exercism/xhaskell#263]
By stepwise doing `all-your-base`, I encountered that a `Just [1]` was expected but a `Nothing` got, while my code was only able to return `Just`s at that stage:

```hs
rebase :: Integral a => a -> a -> [a] -> Maybe [Integer]
rebase inputBase outputBase input =
  let x = fromBase (toInteger inputBase) input
  in Just [x]

fromBase :: Integral a => Integer -> [a] -> Integer
fromBase b = go 0
  where
    go !n []     = n
    go !n (d:ds) = go (n * (toInteger b) + (toInteger d)) ds
```

And I got following test-output (only one out of many):

```txt
### Failure in: 20:both bases are negative
test\Tests.hs:25
expected: Just [1]
 but got: Nothing
```

After changing all occurences of `(~=?)` with `(~?=)` in the `test/Tests.hs` I got a more appropriate output in the testrun:

```txt
### Failure in: 20:both bases are negative
test\Tests.hs:25
expected: Nothing
 but got: Just [1]
```

**Comment by rbasso** [comment]
Thanks for reporting that, @NobbZ.

I guess I confused the operators when writing it. :grin: 

This behavior is already fixed in branch `hspec-fail-fast`...

```haskell
    test Case{..} = it description assertion
      where
        assertion  = expression `shouldBe` outputDigits
        expression = rebase inputBase outputBase inputDigits
```

...but we only had plans to merge it to `master` after migrating the remaining 30 exercises to `Hspec`.

Should we fix that now in `master` or wait for the merge, probably in two weeks?

**Comment by NobbZ** [comment]
I've fixed it locally, so I'm fine with whatever you do :) As far as I did
understand the procedure, @kytrinix needs to sync the tests by hand into
the main repository. So I think we can just let it as is until HSpec is
there.

rbasso <notifications@github.com> schrieb am So., 7. Aug. 2016 um 22:28 Uhr:

**Comment by kytrinyx** [comment]
> As far as I did
> understand the procedure, @kytrinyx needs to sync the tests by hand into
> the main repository.

Yeah basically. We have a separate API that delivers the problem data. It's not a lot of code, but it includes all of the language-specific tracks as submodules, so I have to update the submodules, commit, and deploy, which is still a manual process. I'm sure this could be automated to some degree, but I'm wary of missing something stupid and breaking the site while I'm asleep or traveling.
