### ISSUE TITLE
discussion: Dropping compatibility with older snapshots

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#264]
### Should we keep compatibility with older compilers and libraries?

In some exercises, we are forced to write ugly compatibility code, especially to deal with changes in `base`:

```haskell
-- base >= 4.8 re-exports Control.Applicative.(<$>).
import Control.Applicative -- This is only need for <$>,  if GHC <  7.10.
import Prelude             -- This trick avoids a warning if GHC >= 7.10.
```

It gets worse when we have to use `time`:

```haskell
{-# LANGUAGE CPP #-}

...

#if MIN_VERSION_time(1,5,0)

import Data.Time.Format
  ( ParseTime
  , TimeLocale
  , defaultTimeLocale
  , iso8601DateFormat
  , parseTimeOrError
  )

readTime :: ParseTime t => TimeLocale -> String -> String -> t
readTime = parseTimeOrError True

#else

import Data.Time.Format (readTime)
import System.Locale    (defaultTimeLocale, iso8601DateFormat)

#endif
```

Considering that we demand the usage of Stack in the Haskell track, and that this forces users to run exactly the same compiler and library versions, maybe we could drop compatibility and start writing code using all the new features available in the newest software.

Cons:

- If a user is not using Stack and is also running an older GHC version directly, he/she may be forced to install Stack to be able to run some tests.
- Users will not be exposed to compatibility code.

Pros:

- More beautiful code
- Optimized for happiness.
- Less lines of code.
- Exposes users to new features.
- Saves resources for other Travis-CI users.

Should we do it?

**Comment by NobbZ** [comment]
We are using stack, this does enforce version of ghc used, so I'd think
drop the legacy stuff.

rbasso <notifications@github.com> schrieb am So., 7. Aug. 2016 23:10:

**Comment by rbasso** [comment]
If anyone is against dropping compatibility with older Stack snapshots, say now, or forever hold your peace.

Unless there is a strong argument against it, as soon as `hspec-fail-fast` is merged in `master`, I'll go ahead with this plan.

**Comment by rbasso** [comment]
Considering that there was no opposition almost a month, the support for non-current stack snapshots will be dropped now.
