### ISSUE TITLE
queen-attack row and column mismatch

### ISSUE THREAD

**Issue by JAPJr** [exercism/xhaskell#276]
The comment in Queens.hs states that

-- Positions are specified as two-tuples.
-- The first element is is the column (file in Chess terms).
-- The second element is the row (rank in Chess terms).
-- (0, 0) is the top left of the board, and (7, 7) is the bottom right.

This is the reverse of the ordering of tuples used in the test file, assuming standard depiction of a chess board with white at bottom.  Also, the README.md does not specify the ordering of rank and file.

**Comment by petertseng** [comment]
> This is the reverse of the ordering of tuples used in the test file

Doh. Absolutely my fault, in #207. That should absolutely get fixed.

> Also, the README.md does not specify the ordering of rank and file.

The place to fix that would be https://github.com/exercism/x-common/blob/master/queen-attack.md
