### ISSUE TITLE
roman-numerals: Rewrite to return a Maybe.

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#304]
Considering what was discussed in https://github.com/exercism/xhaskell/issues/194#issuecomment-235112332, we should probably rewrite `roman-numerals` to make it more idiomatic.

Currently, the [reference json file](https://github.com/exercism/x-common/blob/master/exercises/roman-numerals/canonical-data.json) only suggests test for values between 1 and 3000.

Should we really add new tests for:

- Negative values?
- Zero?
- Numbers greater than 3000?

Or should we just change the return type to a `Maybe`, leaving to the user to choose how it will handle those cases?

**Comment by petertseng** [comment]
All the description.md says is "There is no need to be able to convert numbers larger than about 3000.", has not mentioned lower limits. I assume we could test it.

Questions to ask:

* If we change to `Maybe` and add a test for 0, would we expect it to be `Nothing` or `Just ""`?
* If we change to `Maybe` and add a test for -1, would we expect it to be `Nothing` or `Just "-I"`?

I don't know if there is historical basis for the proposed `Just` answers so really I am making things up. If you asked me what I would pick, I'd pick Nothing for both of those, and also a Nothing for 4000.

> Or should we just change the return type to a `Maybe`, leaving to the user to choose how it will handle those cases?

Interesting, we haven't done it before. It could be a worthy experiment. You may recall at #292 I wondered whether people would get confused by that, but maybe if we told them "it's up to you!" then people need not be confused.

**Comment by rbasso** [comment]
> If we change to `Maybe` and add a test for 0, would we expect it to be `Nothing` or `Just ""`?

For historical reasons, I would prefer to use `Nothing`. `Nulla` would probably be too much for the sake of correctness. :smile:

> Interesting, we haven't done it before. It could be a worthy experiment. You may recall at #292 I wondered whether people would get confused by that, but maybe if we told them "it's up to you!" then people need not be confused.

I would favor this approach, using a note in `HINTS.md`.
