### ISSUE TITLE
Tests do not run, no .cabal file found

### ISSUE THREAD

**Issue by hsavit1** [exercism/xhaskell#389]
I'm getting the error message 

$ stack test
> No .cabal file found in directory /Users/.../exercism/haskell/raindrops/

Any reason why?

**Comment by petertseng** [comment]
I can see from https://github.com/exercism/xhaskell/blob/master/docs/TESTS.md#if-you-get-an-error-message-like-this that this probably means you should update your version of Stack - does that seem accurate?

(The content of that file should have gotten included at http://exercism.io/languages/haskell/tests )

Please try that out and let us know if it works, or reopen if it does not.
