### ISSUE TITLE
change: Tests depend on the order of the coins.

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#411]
For a while, we have been generalizing the test suites to allow more diversity in the solutions: #393, #403, #405, #409.

The order of the coins is *not an essential part of the problem*, so it would be nice if the test suite could ignore it. Also, returning multiple equal coins in a list doesn't seems to be the most idiomatic design.

What I propose is to patch to test suite, like we did in #403, to accept:

- Any *Integral* as the amount.
- Anything that can be converted into a list as the input coins.
- Anything`*` that can be converted into an association list of frequencies as the output.

```haskell
findFewestCoins :: Num a => a -> [a] -> Maybe [(a, a)]
findFewestCoins :: Int -> IntSet -> Maybe IntMap
```

Is it possible to accept a `Maybe` or a `Either` :question: 

These are just ideas, and they may increase the complexity of the test suite...

Even if we decide not to do that, we could at least ignore the order of the coins in the tests.

<br>

###### `Multisets` are out of question because they are not instances of `IsList`.

**Comment by petertseng** [comment]
> Is it possible to accept a `Maybe` or a `Either`

I am looking as well but do not find something promising. We could have a typeclass that has instances `Maybe` and `Either`, but it seems like a lot to put it in one test file.

**Comment by rbasso** [comment]
> Seems good, `shouldMatchList` should do nicely here, right?

I don't think it so, because return type is `Maybe []`. I would love to see something similar that works in this case.

**Comment by rbasso** [comment]
Should we change the return type to something more elaborated than a list with repeated coins or should we leave it like this and only ignore the order when comparing?

**Comment by petertseng** [comment]
I was thinking to simply ignore the order; it is then easy to understand what the return type is.

It could be possible to expect something like `[(coin, frequency)]` and ultimately that would be fine, though a little potential for confusion since both will be numbers, unlike with word count where it's `[(word, frequency)]`
