### ISSUE TITLE
Ensuring we are up to date with x-common

### ISSUE THREAD

**Issue by petertseng** [exercism/xhaskell#416]
How should we ensure we're up to date?

One idea is: Every time someone makes a change in x-common, that person is expected to file an issue against all tracks that implement the exercise. If we **rely** on this to happen, then we need take no further action.

Sometimes, that is not always adhered to. We mark dates in our test files, what if we used that to an advantage?

I wrote a short script in https://github.com/exercism/x-common/compare/master...petertseng:up-to-date . Sorry it is not in Haskell, but the idea should be clear:

* read out the date from our test file
* ask x-common if that canonical-data.json file has been changed since that date

In the short term: I will be making some PRs today based on what I've found.
In the long term: Which route shall we take?

**Comment by rbasso** [comment]
The best solution I could find until now is to add the data to `config.json`:

```haskell
  "exercises": [
    {
      "slug": "leap",
      "difficulty": 1,
      "topics": [
      ],
      "x-common-file": "exercises/leap/canonical-data.json",
      "x-common-hash": "cda8f9800a33d997f8c6146a10b8caf66e25ec4b"
    },
    ...
 ```

With this information there, it would be easier to match against x-common:

```bash
$ git diff cda8f9800a33d997f8c6146a10b8caf66e25ec4b exercises/leap/canonical-data.json
```

The only thing we would have to keep in the test suite are the deviations from x-common. 

What do you think about it?

**Comment by rbasso** [comment]
As an example, this shamefull bash script gets the filenames and hashes from `config.json` and checks which files changed in the repository:

#### Beware: Ugly script ahead!

###### checkChanges
```bash
#!/usr/bin/env bash


QUERY='.exercises|map(select(has("x-common-file")))|map({"x-common-hash","x-common-file"})|map("git diff --name-only " + ."x-common-hash" + " " + ."x-common-file" + ";") | .[]';

eval $(jq -r "$QUERY" "$@")
```

It must be run from the root of `x-common`, passing the `config.json` file as an argument:

```bash
.../x-common/ $
.../x-common/ $ checkChanges ../xhaskell/config.json
exercises/leap/canonical-data.json
exercises/space-age/canonical-data.json
...
```

**Comment by petertseng** [comment]
It seems good to use a sha instead of a date - it allows us to check precisely whether the file has changed. That is good.

It may not be necessary to specify the file directly, since they are all `"exercises/" ++ slug ++ "/canonical-data.json"`. I would say it only needs to be specified if it breaks the pattern.

If we move to using the config.json file, I assume we would delete the date lines from the individual Tests.hs files? I wouldn't want to have to maintain our data in two places.

**Comment by rbasso** [comment]
> It may not be necessary to specify the file directly, since they are all "exercises/" ++ slug ++ "/canonical-data.json". I would say it only needs to be specified if it breaks the pattern.

In case of a change in the directory structure we'll have to think about how to deal with that. Considering that most of the json where not changed after the last restructuring, maybe we need to test if it will work without the file.

> If we move to using the config.json file, I assume we would delete the date lines from the individual Tests.hs files?

Agreed!

**Comment by petertseng** [comment]
> In case of a change in the directory structure we'll have to think about how to deal with that.

I am assuming that if there is a change that *all the files change at once* (like what happened with canonical-data.json). In this case, all we need to do is change the file our script looks at, I think?

I will say that in my current script I make use of `git log --follow` to follow renames, but since we want to use `diff` to see whether the file changed, I guess we can't do that.

I admit that I'm not thinking very hard about this because I expect a change in directory structure to be a rare event, and the benefit is that we avoid having to explicitly specify the JSON file. I could be convinced about explicitly specifying if you could convince me about how it deals with structure changes

**Comment by rbasso** [comment]
Ok...I think we can take the risk and forget about the filenames for now. :smile:

**Comment by petertseng** [comment]
OK, so I guess if we want to move to this scheme we just need to start by removing all the date lines and filling in commit SHAs. Should we:

1. Just use the current HEAD of x-common? The only exercises for which we are out of date currently are word-count and triangle, I *think*. So we would just use different commits for those two exercises.
2. Look at the current date of each exercise and try to find in a commit near that date? Seems more work.

**Comment by rbasso** [comment]
The current SHA seems good enough.

I don't care too much about what is currently not following x-common. Detecting changes from now on seems good enough.

**Comment by rbasso** [comment]
```json
accumulate "x-common-hash": "aa67cade08b3b6a80bb9dad210409f29bb9e25ed"
all-your-base "x-common-hash": "b00a52a769a9b8eb392057089a6c4ffac264d302"
allergies "x-common-hash": "be679ece1f844453d32939ffbb00939117a66f7a"
alphametics "x-common-hash": "87473676d381132e0900842bf2c711c8ebb68ee8"
anagram "x-common-hash": "4b4db255c7e41f5831b3f2a81471be1c93a831cd"
atbash-cipher "x-common-hash": "f15834ffe513461f53b0d02cf64adbdbc8f9a97a"
bank-account "x-common-hash": "fd8893435a46f39d9b4ee647b19b1bec4a2d106e"
beer-song "x-common-hash": "63a60b133bd13b95b49c496c693d04922e27c33c"
binary-search-tree "x-common-hash": "a100c796165d5e10f55ff298b8589c3843c03f7b"
binary "x-common-hash": "e593aa562efd0d93418cac70730433c8c7b1297d"
bob "x-common-hash": "c1de9fc2f6ca55e689379794928d1a2ab9d4163d"
change "x-common-hash": "eb53ada3d9b7d4fc799e5e6c5952f0bc1e55543c"
clock "x-common-hash": "1085972537382fabadf23f2f41d88f1f8ca7b3ec"
connect "x-common-hash": "37a7127e87a5270c70430ad879dc8da53e30ce43"
crypto-square "x-common-hash": "d1d6097d9d5fd0c8dc1aaad0a882c24ea8302632"
custom-set "x-common-hash": "b5a50ab3a73a4cf322b31a8edf4b940ca4df45b3"
difference-of-squares "x-common-hash": "754dc73ad4e05da9b1b80679e4e84873888fb1c8"
etl "x-common-hash": "170a44a755f8ec6d8f8d7aea475f3ed9c9de3b84"
food-chain "x-common-hash": "9562b0f9a1d92804ad2673da3ca6f6661fed1de7"
forth "x-common-hash": "48f75cf65166d85f22ab5b7f4817eb820f534676"
gigasecond "x-common-hash": "93ca5082dba707fb545c125eeade5e8d4b2da670"
go-counting "x-common-hash": "63b9dc50964e4cdb6572237670efa7b3757c5520"
grade-school "x-common-hash": "e58cc30079661eb5f91d1d0c7319597da4785d25"
grains "x-common-hash": "ae2258be88583202d440c2094ca79f568413a7b3"
hamming "x-common-hash": "cc215d77017e691318100f6d782fa6a34c8e24f9"
hexadecimal "x-common-hash": "ee8b4c81f83fccd41dc4efdcee85a9511415dc08"
house "x-common-hash": "05f873bf1a0516c0880fec7ca2c0b60005493126"
kindergarten-garden "x-common-hash": "c778480eee80a1cfa2e1a4ce9a59f54e89a06f1c"
largest-series-product "x-common-hash": "aa47e6c53646d4ed0d97f503eea6024bb46149be"
leap "x-common-hash": "586ef70b011c0efc612bc373e946a8d1c85da88d"
lens-person "x-common-hash": "71ddd7487f64010283afc214073b5cfe18c97a0a"
linked-list "x-common-hash": "3e815ee2617ebd3850fc01b3eb1378ebbba5e3bc"
list-ops "x-common-hash": "396270ada04aef66d298b7d2dbc89bb1bbf3fd2d"
luhn "x-common-hash": "f4455d02111f71e69ed8d6b7597672354b90de24"
matrix "x-common-hash": "c7981eb67b6881377e9ff32e7510c2f6c0176c3f"
meetup "x-common-hash": "64c355a15a5643ada0312edaa2b9406b6fbf9d95"
minesweeper "x-common-hash": "8ed20c64a10e496a5b5b19e09985274c2b13149c"
nth-prime "x-common-hash": "5dc139c42bf17a6ed44d297f654bed74a61636fc"
nucleotide-count "x-common-hash": "5bcac9f48e76b56f62b51be29aa49018040d1ae7"
ocr-numbers "x-common-hash": "c2e17c36eba193125c4887e592d211e26796d209"
octal "x-common-hash": "4e9bb47f21100a215e1e4ccf80933d254e045246"
palindrome-products "x-common-hash": "36d75c1b9c4044075513b61179de38bc0e5d6468"
parallel-letter-frequency "x-common-hash": "0e178e1ac6d236789df2bb7cd6239b77f4359b7b"
pascals-triangle "x-common-hash": "34b39905236ad4775a7a14b05fc6a241431d4413"
phone-number "x-common-hash": "0b1426d0214481dee822d039feede9643119549f"
pig-latin "x-common-hash": "b098e408facb91dcc773cec487a05477adb9cc58"
pov "x-common-hash": "968961c07bc4a0011ce1a6d34e99a5482ef05f02"
prime-factors "x-common-hash": "2b1b8b5b23d06e8675168c9e69ca25cc41cb456b"
pythagorean-triplet "x-common-hash": "b07a2c05cc7dc90cfcfcac83b4cb402f755798d2"
queen-attack "x-common-hash": "d503add9f3cb3c4055a5b97147aba694fc46aced"
raindrops "x-common-hash": "e613d5742f0815ecad6fc41a877799d158520ef7"
rna-transcription "x-common-hash": "77324b6744a0eb067cc8490f05e55294b2fa5a35"
robot-name "x-common-hash": "9f47c53c9e67b1747b06c198760cf8fc99f33535"
robot-simulator "x-common-hash": "b11a069b690b586b7c8df0602cdb0364ea2a4e98"
roman-numerals "x-common-hash": "02aaccf8ae54471e93678e0ee65e5c2362b15360"
saddle-points "x-common-hash": "e043acd2441a149a5acc3035d6c6a686fec0c76d"
say "x-common-hash": "fe97dde623b39f8d3ae4f0ca663586781ccc6385"
scrabble-score "x-common-hash": "db7a23a95b71d94bea30d1457e83dc85042bcd3a"
secret-handshake "x-common-hash": "27ff97e16bca4601bf45579fa2303f641dea1ae9"
series "x-common-hash": "2771e698a7b4fc0447868a94f058a92338ed0108"
sgf-parsing "x-common-hash": "6237766a52b0c7400025b0eaf69d830c26202433"
sieve "x-common-hash": "057bd7e83399ad6402849e24b235b83dc7b9d77c"
simple-cipher "x-common-hash": "74bd6b182879cb07f005744d6eebf2a4faadfc20"
simple-linked-list "x-common-hash": "29fdf0d72d8ff8c63ff04ef5e465f1ce34720d65"
space-age "x-common-hash": "e28f6300ae0fb59c34aeb5ab8117b1ea1e3dba4e"
strain "x-common-hash": "6dce4d35b341216cf5fb547308208994f316c61b"
sublist "x-common-hash": "bf3482ad38fda90e44a915ea2659ae4f5890389b"
sum-of-multiples "x-common-hash": "1cf92f90be1fedb15133645c40f1d364cf1bc59d"
triangle "x-common-hash": "69d0e5f17c549ee8af65a06d001632732950fd70"
trinary "x-common-hash": "93de6e71dc6d847368e3780e455e4105932dd920"
word-count "x-common-hash": "738b4042c0b29cc7519ca2ba183118cdc6ad5be3"
wordy "x-common-hash": "544bca6d3e10e8ab4370a2e2c4275472f3abf4ff"
zebra-puzzle "x-common-hash": "039c3a2676d38d583139516b3f708c9a433c767b"
zipper "x-common-hash": "7d103e7740446724c68c52755622219a6be48986"
```

Now we just need to insert all this in `config.json`.

**Comment by petertseng** [comment]
Going to ask real quick, thoughts on placing all the data in config.json instead of the individual test files?

config.json:

* won't get shown to students, so they won't see irrelevant info they don't need to worry about
* is all in one file, if that helps (does it?)
* very easy to understand how to parse it (JSON), not clear how to find it if we bury it in the file (just grep for 40 [0-9a-f] characters in a row?)

individual test files:

* probably harder to forget to change it
* if I ask the question "when was accumulate updated?" it's probably easier to understand if I know I look in accumuate's tests, instead of look for it in JSON

It's probably not that hard to write something to insert in the `x-common-hash` to all exercises right now.
Note it's not a super high priority for me right now since currently looking at the date works and I honestly think that we (mostly you) made sure we were up to date pretty well when doing the `hspec` rewrites. So I might focus on some other things first.

**Comment by rbasso** [comment]
Humm....I think that the deviations from `x-common` should stay in the test suite. It's not a problem if the students look at it, in fact it could be useful, because a lot of them already know the exercise from other tracks, also they can become contributors.

Yeah...It is probably better put put everything in the test suite.
I'm not sure about the format and position.

**Comment by petertseng** [comment]
I should probably mention this here while we are thinking about this subject - another alternative is to write test generators for those exercises that have canonical-data.json

I have to honestly say that my current perceived benefit of writing the test generator is not high enough to justify the costs that I anticipate. I'm willing to have my mind changed on that, of course.

**Comment by rbasso** [comment]
The frequency of updates to exercises in this track is high, but most of the changes are not caused by minor changes in `x-common`. I think that, if we automatize test generation, we would innovate less.

**Comment by petertseng** [comment]
Might as well link to https://github.com/exercism/x-common/issues/524 so that I can see it from here later.

I have no further updates right now. I run that script from time to time when I feel like it, and if I see something interesting I update this track.

**Comment by petertseng** [comment]
If we update all our test files to use the scheme proposed in https://github.com/exercism/xhaskell/pull/511#discussion_r109304527

```
Adapted from
Source: exercism/x-common/exercises/pangram/canonical-data.json
Version: 1.0.0
Date: 2017-03-28
```

Then, we can use a version comparison to see whether there are new changes. So, it could be useful to open a new issue to get every file to display its version.

**Comment by petertseng** [comment]
Consider the technique described in https://github.com/exercism/discussions/issues/133.

**Comment by rbasso** [comment]
When we run the tests, *HSpec* displays the package version from the `package.yaml` file, which we don't set at the moment, so the user get something like this:

```
leap-0.0.0: test (suite: test)


leap
  isLeapYear
    1996 - leap year
    1997 - standard and odd year
    1998 - standard even year
    1900 - standard nineteenth century
    1800 - standard eighteenth century
    2400 - leap twenty fourth century
    2000 - leap y2k

Finished in 0.0002 seconds
7 examples, 0 failures
```

It would be great if we could display the test-suite version at the top line!

What about setting the version in the delivered `package.yaml` as a way to keep track of the canonical data versions?

To make things easier for us, we could use the following versioning: `canonicalVersion.SERIAL`. For example:

Old version:
  - Old canonical version: 1.2.3
  - Old serial number: 100
  - Old test suite version: 1.2.3.100

New version:
  - New canonical version: 1.2.5
  - New serial number: 100 + 1 = 101
  - New test suite version: 1.2.5.101

Starting the SERIAL at `1` seems reasonable to me.

Exercises that do not follow the canonical-data test could use `0.1.0.SERIAL`, which makes their version greater than the default `0.0.0` but smaller than any canonical data, which start at `1.0.0`.

The important thing about the serial number is that it would have to increase on any change. Instead of increasing by a unit it could be a date in the format `YYYYMMDD`, but I'm not sure if that would do any good, and two changes in a single day would have the same version.

Using the proposed versioning in `package.yaml`, the outdated test suites would be the ones where `canonicalVersion > testSuiteVersion`. One problem with this approach is that the exercises not tracking as existing `canonical-data.json` would be always be flagged outdated. 

Considering that `canonical-data.json` is JSON and `package.yaml` is YAML, I guess that writing a small script to compare both repositories wouldn't be too hard, but seems an interesting practice with Aeson.

The annoying thing with this way of versioning is that we would have to update two files instead of one (`package.yaml` and `test/Tests.hs`), but it seems more similar to how a real application would do it.

So...what do you think about it @exercism/haskell?

**Comment by petertseng** [comment]
Oh, that seems good.

The date is not particularly important now that x-common has versions. We could remove it from the test files too. Should we?

It would not have been terrible to use YYMMDD in the serial since typically there is only one trackler update a day, but since the boundary doesn't always lie on midnight (and timezone considerations) starting at 1 seems better anyway.

**Comment by rbasso** [comment]
> The date is not particularly important now that x-common has versions. We could remove it from the test files too. Should we?

I think that the only thing we need to annotate in the test suites are the divergences from `x-common`, and only if the exercise follows a `canonical-data.json`.

> ... but since the boundary doesn't always lie on midnight (and timezone considerations) starting at 1 seems better anyway.

👍

**Comment by petertseng** [comment]
Currently doing well! Currently out of date on:

                  phone-number: 1.0.0.2 -> 1.2.0
                      list-ops: 0.1.0.1 -> 1.0.0
                          luhn: 0.9.0.1 # 2016-08-04 -> 1.0.0
                           pov: 1.0.0.2 -> 1.1.1
                roman-numerals: 0.9.0.1 # 2016-07-26 -> 1.0.0
                          leap: 0.9.0.1 # 2016-07-27 -> 1.0.0
                       bowling: 0.9.0.1 # 2016-11-20 -> 1.0.0

**Comment by petertseng** [comment]
we might in fact be up-to-date on bowling, I just didn't check

roman numerals only needs descriptions to be up to date.

**Comment by petertseng** [comment]
I'm a bit too lazy to make list-ops match right now, so I won't. I did verify that we test the same functions and all cases seem covered well enough.

**Comment by rbasso** [comment]
All exercises in `xhaskell` and files in `x-common` are now versioned, and we also have [some tools](https://github.com/exercism/xhaskell/issues/522#issuecomment-299781442) to check for updates.

Is there anything else missing here or can we consider it solved, @petertseng?

**Comment by petertseng** [comment]
Let's discuss one last thing: How shall we remember to keep up to date?

An acceptable answer could be "We just run whatever tool we have on a manual but periodic basis", which is a simple solution. I'll add it to #470 for now, and if we decide on this solution, we can close this issue.

The other solution is that of https://github.com/exercism/discussions/issues/133 which puts something in the CI to check that any file that **gets changed** is up-to-date. This is nonzero extra effort and also might still cause us to not discover an out-of-date exercise for a long time if its files do not get updated. So we would have to be careful about that.

Another solution is to always check all versions in CI, but I don't like this solution because then a previously-passing build may turn into failing through no fault of our part.

So if there is no better solution the best may simply be "We will just run it on a periodic basis". Tell me if there are any better ideas.

**Comment by petertseng** [comment]
I have raised the question on x-common, but we will probably make our own decision since I don't know how many tracks have exercises versioned (I think Ruby and OCaml) and script ready to run (all four listed at https://github.com/petertseng/x-common/tree/up-to-date/up-to-date, plus Python)

**Comment by rbasso** [comment]
My understanding that Travis-CI can only check if a branch is in a **working state**. From this, follows some simple rules:

1. It shouldn't depend on anything except the repository.
2. It shouldn't depend on past versions of the repository.

The build environment, `configlet` and `stack` are mostly unavoidable exceptions to the first rule, but hopefully they'll change little. The *cache* is a huge exception to the second, so I try to clean it from time to time, just to be sure that everything builds from scratch.

The situation may not be ideal, but I don't think we should make it worse adding `x-common` as an additional source of surprises.

Unless I'm completely missing something in exercism/discussions#133, there is only one thing that can be done without creating problem in Travis-CI:

- Run the report to see what exercises are outdated, without affecting the build result.

This would increase complexity and doesn't seem to save much manual work IMHO, but it is possible.

**Comment by petertseng** [comment]
> * Run the report to see what exercises are outdated, without affecting the build result.
>
> This would increase complexity and doesn't seem to save much manual work IMHO, but it is possible.

I agree with all of this. In addition:

It helps make the results of the script accessible to contributors that are not ourselves, but I think there is a low chance anyone except ourselves is really interested in it.

If it doesn't affect the build result it may also be easy to miss; some people may not even be aware it's there.

An advantage is that it gives us logs for free of how up-to-date we were at any given point in time (as long as Travis CI is willing to keep our build logs), but I haven't seen any demand for that.

I also don't want people to get into the practice of starting a new build for the sole purpose of seeing the tool's output (it would probably be better to just run the script).

These factors make me not that motivated to add it. So I will not for now, though anyone is free to make the PR and we could discuss again.

So I will leave this as a task to run periodically, in #470.

**Comment by NobbZ** [comment]
There is a beta feature in Travis, which might help you

https://docs.travis-ci.com/user/cron-jobs/

Peter Tseng <notifications@github.com> schrieb am Di., 16. Mai 2017, 21:50:
