### ISSUE TITLE
presenting clean package.yaml to students

### ISSUE THREAD

**Issue by petertseng** [exercism/xhaskell#420]
Since #396 we can move our examples to a separate directory with its own `package.yaml` to prevent showing students extra elements in dependencies in `package.yaml`

Here are the current exercises with non-empty dependencies.

It should be pretty easy to script the process of moving them all at once. The question before doing that: Are there any exercises where we should just keep the `package.yaml` as-is?

- [ ] atbash-cipher: split
- [ ] bank-account: stm
- [ ] connect: array
- [ ] crypto-square: split
- [ ] food-chain: array
- [ ] go-counting: array
- [ ] grade-school: containers
- [ ] kindergarten-garden: containers, split
- [ ] largest-series-product: safe
- [ ] lens-person: lens
- [ ] linked-list: stm
- [ ] ocr-numbers: containers, split
- [ ] parallel-letter-frequency: parallel
- [ ] rna-transcription: containers
- [ ] robot-name: random
- [ ] saddle-points: containers
- [ ] say: array
- [ ] scrabble-score: containers
- [ ] sgf-parsing: attoparsec
- [ ] sieve: vector
- [ ] simple-cipher: random
- [ ] triangle: containers
- [ ] wordy: attoparsec, text

**Comment by rbasso** [comment]
IMHO, the only reason to provide a `package.yaml` with dependencies in the library section is if is impossible to solve without it, because of the test suite demands it, or if the stub solution uses it:

- `go-counting` needs `containers`.
- `kindergarten-garden` needs `containers`.
- ...

I haven't checked all of them yet.

**Comment by rbasso** [comment]
I removed all dependencies that where not used by the stub solutions or demanded by the test suites, but the process was far from automatic. :tired_face: 

> It should be pretty easy to script the process of moving them all at once.

**Comment by petertseng** [comment]
> but the process was far from automatic. 

Oops :<

Oh well, at least we only have to do it this once, right? So this issue is closed now, right?

**Comment by petertseng** [comment]
Oh wait, you were doing that in #423. Okay, I'll leave it open until then.

**Comment by petertseng** [comment]
Coming in real quick to mark down a reference - this fixes a flaw first noted in https://github.com/exercism/xhaskell/pull/189#r70165604
