### ISSUE TITLE
difference-of-squares: test problem

### ISSUE THREAD

**Issue by concernedsyndicate** [exercism/xhaskell#433]
Hi. The issue is:
That's the first and(so far) only test with this kind of message.

C:\Users\LENOVO\Desktop\funcional-programming\Haskel-exercises\exercism\haskell\difference-of-squares>stack test

difference-of-squares-0.0.0: build (lib + test)
Preprocessing library difference-of-squares-0.0.0...
Preprocessing test suite 'test' for difference-of-squares-0.0.0...
[1 of 1] Compiling Main             ( test\Tests.hs, .stack-work\dist\b7fec021\build\test\test-tmp\Main.o )
Linking .stack-work\dist\b7fec021\build\test\test.exe ...
difference-of-squares-0.0.0: copy/register
Installing library in
C:\Users\LENOVO\Desktop\funcional-programming\Haskel-exercises\exercism\haskell\difference-of-squares\.stack-work\install\4eba3826\lib\x86_64-windows-ghc-8.0.1\difference-of-squares-0.0.0-i6De56LKW04sg4yY7d7KT
copyFile: does not exist (System nie mo?e odnale?? okre?lonej ?cie?ki.) (system couldn't find path)
'cabal copy' failed.  Error message:

--  While building package difference-of-squares-0.0.0 using:
      C:\Users\LENOVO\AppData\Roaming\stack\setup-exe-cache\x86_64-windows\setup-Simple-Cabal-1.24.0.0-ghc-8.0.1.exe --builddir=.stack-work\dist\b7fec021 copy
    Process exited with code: ExitFailure 1

One possible cause of this issue is:
* No module named "Main". The 'main-is' source file should usually have a header indicating that it's a 'Main' module.

**Comment by rbasso** [comment]
I just run `stack test` in my machine, using the stub solution, and here it works.

Are you running the exercise unaltered or have you changed anything?

One important question. Are you running the latest *Stack* version?

**Comment by rbasso** [comment]
Try to reproduce your problem in a clean subdirectory outside of exercism's folder.

You will need the following directory structure:

```
stack.yaml
package.yaml
src/Squares.hs
test/Tests.hs
```

Are you able to reproduce the error in these conditions?
If yes, please share the source of your `Square.hs` file.

**Comment by concernedsyndicate** [comment]
I tried and problem is gone. My best guess is that path to some file was too long.

**Comment by rbasso** [comment]
In that case I'll close this issue for now.

If the problem show up again, we can certainly reopen it. :+1:
