### ISSUE TITLE
stack.yaml: Avoiding multiplicity

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#442]
All exercises in the Haskell track have exactly the same `stack.yaml` file. We do that to minimize downloads and keep a minimum of coherence.

Having 76 identical files is so ugly....

There was a short discussion about a solution to that in https://github.com/exercism/x-api/issues/29#issuecomment-237160865, but it seems that the idea was abandoned, and the discussion is now only about having files to be deployed outside the exercise's directory.

Possibly this track is alone in the need for a feature to deploy the same file to all exercises.

An alternative solution, almost equally ugly, is to symbolic link all `stack.yaml` files to the same one, outside the exercises folder.

A short discussion in Gitter indicated that the symbolic links would work, delivering the contents of the targeted file.

This if far from perfect, because we have to be sure that all exercises have the same symbolic links in place, but is not harder than checking if all the exercises have identical files. The advantage would be to allow us to update just one `stack.yaml` instead of 76, every time that we need to update the *resolver*.

If we decide to follow this path, first we should make a test, just to be sure that the symbolic link works as expected.

What do you think about it? @exercism/haskell @abo64. 

---

**Edit:** *On hold* until https://github.com/exercism/trackler/issues/13 is solved.

**Comment by rbasso** [comment]
All exercises in the Haskell track have exactly the same `stack.yaml` file. We do that to minimize downloads and keep a minimum of coherence.

Having 76 identical files is so ugly....

There was a short discussion about a solution to that in https://github.com/exercism/x-api/issues/29#issuecomment-237160865, but it seems that the idea was abandoned, and the discussion now only about having files to be deployed outside the exercise's directory.

Possibly this track is alone in the need for a feature to deploy the same file to all exercises.

An alternative solution, almost equally ugly, is to symbolic link all `stack.yaml` files to the same one, outside the exercises folder.

A short discussion in Gitter indicated that the symbolic links would work, delivering the contents of the targeted file.

This if far from perfect, because we have to be sure that all exercises have the same symbolic links in place, but is not harder than checking if all the exercises have identical files. The advantage would be to allow us to update just one `stack.yaml` instead of 76, every time that we need to update the *resolver*.

If we decide to follow this path, first we should make a test, just to be sure that the symbolic link works as expected.
 
What do you think about it? @exercism/haskell @abo64.

**Comment by petertseng** [comment]
The advantage of only having to update stack.yaml once seems beneficial enough. If it makes life harder for new contributors, we can try to help with instructions. So I would support it becoming a symlink.

This is unrelated to whether we use a symlink or a regular file, but we could have an automated check for whether all the files needed for an exercise are present. In fact, we probably already implicitly do - if any file isn't present, would Travis CI fail to run that exercise?

**Comment by abo64** [comment]
+1 for symlink.
Btw, isn't there also some redundancy for `package.yaml`? If naming conventions are uniform one could also imagine some common file here, and only state additional dependencies?

**Comment by rbasso** [comment]
> This is unrelated to whether we use a symlink or a regular file, but we could have an automated check for whether all the files needed for an exercise are present. In fact, we probably already implicitly do - if any file isn't present, would Travis CI fail to run that exercise?

I believe it would fail....but I'm not sure.

I guess that what we are missing is a tool to test an exercise, and this would also be useful for contributors. I started to write something like that in Haskell (as a stack script) @petertseng, but I gave up and I don't have plans to try again so soon. :grin: 

> If naming conventions are uniform one could also imagine some common file here, and only state additional dependencies?

It would certainly be possible, but that would add some complexity. If there is an easy solution, I would certainly agree with that, but everything I imagined was too ugly...

**Comment by rbasso** [comment]
Considering [this comment](https://github.com/exercism/xhaskell/pull/507#issuecomment-287500563), I think it may be time to revert #454, and maybe remove the `common` folder and close this issue.

**Comment by petertseng** [comment]
> revert #454, and maybe remove the common folder and close this issue.

Yup.

I would like for symlinks to work, but https://github.com/exercism/x-common/issues/601 has rightfully brought up concerns that symlinks may not be supported on all platforms, which means that if we use symlinks, we may prevent certain people from using the repo.

I don't have a good solution for that, so unfortunately I think we can't proceed with this experiment in the near future. We will have to try using other means to ensure we keep our stack.yaml all the same.

**Comment by petertseng** [comment]
Today (trackler version 2.0.8.33), if you fetch `pov` you will receive the `.dummylink` file with correct contents. You can see this is true by examining "dummylink" in http://x.exercism.io/v2/exercises/haskell/pov. I wonder if it will stay true.

This fact has been reported at https://github.com/exercism/trackler/issues/13.

**Comment by rbasso** [comment]
Nice. 😄

**Comment by petertseng** [comment]
Even though it happened to work for 2.0.8.33 and 2.0.8.34, I would be reluctant to rely on it. Should still probably remove the .dummylink, just not as urgent now that the readme isn't broken.
