### ISSUE TITLE
Notes regarding "Require branches to be up to date before merging" 

### ISSUE THREAD

**Issue by petertseng** [exercism/xhaskell#445]
They're in #444 

I just created this issue to help me find them easier.

If we revert it:

For the situation of "Branches A and B individually pass the tests, but together they would fail", the procedure of:

* Merge A
* Click "Restart build" on B

will then cause the Travis CI check for B to fail (as it should), but the disadvantage is we'd have to remember to click that "Restart build" button, and we might forget (because we are all human).

So we will leave it as is for now!

I don't need comments on this issue, I'm going to close it immediately.

I think I would like an email for this though, so maybe someone could comment on it and then delete their comment (if necessary)?

**Comment by rbasso** [comment]
Commenting just to notify @petertseng.

**Comment by petertseng** [comment]
I got really annoyed that I created 6 PRs in a row, but the "Require branches to be up to date before merging" would have forced me to merge one, update the next one, wait 5 minutes for build to pass, and so on, taking 25+ minutes to merge the PRs. After merging the first two, I got fed up and just octopus merged them all.

https://github.com/exercism/xhaskell/commit/381d33942c62bcad6dbbba56a0ae373e1b2f69c5

command-line only, and you have to make Travis build that commit on a branch before it can be pushed to master, but at least it's better than waiting 5 minutes per PR.

**Comment by petertseng** [comment]
That means ultimately I **don't** need this setting changed, since I (finally!) found a way to fit it into my workflow (octopus merge) that doesn't make me go insane.

However, if octopus merges make anyone other than me go insane, then the only way to resolve our differences may be in fact to change that setting. Because I will go insane without octopus merges.

**Comment by rbasso** [comment]
Ideally, this setting makes sense, but I also think that it is annoying.

The probability of having commits that pass individual tests but fail the combined ones is remote and would be detected in the next PR. So it seems that there is almost no risk in disabling it.

Feel free to ask Katrina to disable it. 👍

**Comment by petertseng** [comment]
Hmm, now I'm not sure how I got the octomerge to work last time. I'll keep trying a bit but eventually I may have to merge without it if I can't figure it out.

**Comment by petertseng** [comment]
Okay that worked... variables to check:

* Does it matter whether approvals on all PRs need to be for the latest commit on that PR? I **thought** yes this time, but wasn't sure.
* Does it matter whether master is listed as one of the parents of the merge commit? Can it not be, if branches are fast-forwards? I **thought** this also made it not work, but also unsure.

I was unsure because originally the merge got rejected, but I couldn't tell which of the two factors it was.

**Comment by petertseng** [comment]
ebwodp:  see how I needed to ask for re-approval on #533, #534

**Comment by petertseng** [comment]
ebwodp: Is it OK for master not to be listed, if branches are fast-forwards

**Comment by petertseng** [comment]
Historical notes: Octomerges performed in this repo:

* https://github.com/exercism/haskell/commit/381d33942c62bcad6dbbba56a0ae373e1b2f69c5
* https://github.com/exercism/haskell/commit/a142b266120bd2e50354991a994346bb57a03687

I wrote down the former, but not the latter.
