### ISSUE TITLE
Better documentation to help contributors

### ISSUE THREAD

**Issue by abo64** [exercism/xhaskell#448]
As a point for discussion here are some items we should provide to help contributors. I stated them in the form of a little Q&A.
What is missing? and @rbasso already pointed out we should avoid any duplication of `x-common` documentation.

##### Do I need to be a seasoned Haskell expert to contribute?
- no, anybody can!
- even a simple contribution like a typo fix is welcome!
- or a comment in PR or Issue (?)
- ofc it should somehow be helpful

##### Issue or PR - which one should I use when?
- links: how to create them

##### What is the directory structure of an exercise?
- directories
- files: naming conventions and content

##### Are there any standards for Haskell source code?
- code formatting
- use hlint and -Wall

##### What is there to know about the template .hs file?
- as general as possible to not exclude any solutions
- no comments b/c people tend to not delete them
- instead add a HINTS.md if necessary (link to existing file)
- "data X = Dummy"
- link: some existing template

##### What about the example solution?
- what is it for
- where to put it
- library dependencies
- TestSuite runtime limits

##### What of Tests.hs?
- use existing tests of `x-common`
- use Haskell specifics like `Maybe` or `Either` when it makes sense
- if you find missing tests add them to `x-common`, too
- link: some existing Tests.hs

##### What should I know about github? (and perhaps Travis, ...)
- links: git comments, squashing

##### Where can I turn to for discussions, further questions, comments?
- links: gitter.im/exercism/support, exercism/discussions

**Comment by rbasso** [comment]
Seems great! :+1: 

Anything to add/remove, @petertseng?

Fell free to open a PR if you decide to write it @abo64, then we can discuss it in a more concrete context.

**Comment by abo64** [comment]
@rbasso yes, I will do when I have @petertseng 's feedback, too.

**Comment by petertseng** [comment]
Thanks. I feel like I can only add a few small things, since the proposed list has covered a lot of good points.

I haven't seen any contributors get confused by this one, but if someone asks "where does the README come from?" and/or would submit a PR with a README.md for a new exercise, maybe we can mention they come from x-common.

Maybe a mention that if contributing a new exercise, need to add it to config.json.

The [xgo README](https://github.com/exercism/xgo) even has screenshots of what it looks like to make a PR, though I don't know that we need to go that far.

**Comment by abo64** [comment]
@petertseng good points, thank you.
Rather than screen shots I want to include links from Github Help like [Creating a pull request](https://help.github.com/articles/creating-a-pull-request/) or [Creating a pull request from a fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/). One probably cannot do better than that.
Perhaps I will just write a first draft and create a PR. And then I expect heavy changes in the review process.
