### ISSUE TITLE
discussion: Test cases about memory and/or performance: Should we have them?

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#452]
As we can see from #449, tests that involve huge numbers or big lists can be hard for beginners.

Reasoning about memory usage and performance is hard in Haskell - as least for me - but it is even harder for students that are solving a problem and usualy don't know exactly how big is the data used in the tests.

On the other hand, someday students will have to face those problems...

The test cases involving speed are not a huge problem, but I still believe that supplying benchmarks would be a better solution, separating distinct concerns: correct behavior and speed.

Test cases about memory are really problematic, because, as mentioned [in this comment](https://github.com/exercism/xhaskell/issues/449#issuecomment-264704443) they could crash your OS.

What do you think about? What should we do?

**Comment by tewe** [comment]
`GHCRTS='-M128m'` or `ulimit` could be used to avoid eating too much memory. As space-efficient algorithms are usually dramatically so the tests should still be achievable.

**Comment by rbasso** [comment]
I'll take a look at that to see if it I find a way to pass options to GHC when running the test suites. That could be interesting to avoid students some problems.

**Comment by rbasso** [comment]
While we can limit the amount of memory used when testing the exercises adding...

```json
ghc-options: -with-rtsopts=-M128m
```

to `package.yaml`, that wouldn't avoid the problem when testing the exercise with `stack ghci`.

The users could run `stack ghci --ghci-options '+RTS -M128m -RTS'` by themselves, but it seems there is not way to set that in the configuration. So even if we enabled memory limits for all exercises, the user wouldn't be safe from shooting itself in the foot.
