### ISSUE TITLE
roman-numerals: No test cases for `Nothing`?

### ISSUE THREAD

**Issue by abo64** [exercism/xhaskell#460]
The return type of `Roman (numerals)` has been changed to a `Maybe`, but there are no test cases for `Nothing`? Shouldn't we add some for this to make more sense?

Another question that came to my mind: This exercise (or a new one) could also include the inverse conversion from Roman numeral to an `Int`? Would be cheap to add as one could just reuse the existing test cases.

**Comment by rbasso** [comment]
> The return type of Roman (numerals) has been changed to a Maybe, but there are no test cases for Nothing?

This was the result of the discussion in #304, implemented in #328.

This way the type shows that the conversion is not always possible, but leave students the ability to extend the solution, dealing with numbers bigger than 3000.

> Shouldn't we add some for this to make more sense?

I would avoid testing against anything bigger than 3000.

About zero and negative numbers, @petertseng's [comment](https://github.com/exercism/xhaskell/issues/304#issuecomment-248190387) summarizes the options.

> Another question that came to my mind: This exercise (or a new one) could also include the inverse conversion from Roman numeral to an Int? Would be cheap to add as one could just reuse the existing test cases.

Seems a nice idea!

`toRoman` and `fromRoman`?

**Comment by rbasso** [comment]
It would be nice if Haskell had a type for strictly positive numbers...

For non-negatives I found [Natural](https://hackage.haskell.org/package/base-4.9.0.0/candidate/docs/GHC-Natural.html), that now is part of **base**, but that still leaves zero. I guess what I really want are dependent types. :)

**Comment by abo64** [comment]
@rbasso Yes, that would be nice. Or have a `Bounded` instance for now? :)

`toRoman` and `fromRoman` sounds good.
What about changing `x-common`, too?

**Comment by rbasso** [comment]
> What about changing x-common, too?

Not sure if we should do that. Dealing with exceptional values is very language-dependent, and some languages are probably using unsigned number and cannot test for negative numbers.

**Comment by abo64** [comment]
@rbasso No, I meant about adding `fromRoman`?

**Comment by rbasso** [comment]
Did you find anything there that makes reference to the direction of the conversions?

**Comment by rbasso** [comment]
Did you find anything there that makes reference to the direction of the conversions?

**Edit:** If you want to make it clearer there that the conversion can be made in both direction, of course it can be changed. 👍

**Comment by abo64** [comment]
Is that something that could be discussed on `gitter/exercism/dev`?

**Comment by rbasso** [comment]
Sure!

**Comment by abo64** [comment]
What shall we do about this one?
The `gitter/exercism/dev` discussion didn't really pan out (yet?).

**Comment by rbasso** [comment]
It seems that `fromRoman` was not so popular there, so I don't think that the idea of changing it in `x-common` will go forward.

The conversion from roman numerals seems to be a very different problem from the reverse one, and is also a little harder, right? So I see the point that it may not be part of the same exercise.

What I think that makes it interesting is that it parses in a very unusual way, e.g.:

```
CIIX = C + (IIX) = C + (X - (II)) = C + (X - (I + I))
```

But I don't know if that, by itself, will make an interesting exercises.

In fact, I have no idea of what makes a problem interesting and sometimes I get really surprised about some exercises. For example, `all-your-base` is less interesting than I expected, but `leap` and `raindrops` are much better than I imagined.

**Comment by abo64** [comment]
Don't know if I understand you here correctly: Isn't `CIIX` just invalid and should result in a `Nothing`?

But I agree that `fromRoman` is actually a different exercise, too far away from `toRoman`.

I guess what is interesting is a matter of individual taste and knowledge (and what effort you are willing to invest) more than anything else. A beginner will probably come to a very different judgement from yours. :)

**Comment by rbasso** [comment]
Sorry...bad example. Invalid. :)

**Comment by abo64** [comment]
In fact I do have a local `x-common/exercises/roman-decode` ready.
I am only a bit afraid about the possible PR discussions and changes. To contribute to `x-common` seems somewhat difficult at times with all the different people and their opinions. :)

**Comment by petertseng** [comment]
If the thought is that fromRoman would not be accepted to x-common, then as of https://github.com/exercism/trackler/pull/24 it is possible to this track to define it as a track-specific exercise.
