### ISSUE TITLE
data and constructors required by tests: Should we provide them in stubs?

### ISSUE THREAD

**Issue by petertseng** [exercism/xhaskell#466]
See in https://github.com/exercism/xhaskell/pull/464#discussion_r95073688 how I argued:

* The test is expecting the four constructors
* If we don't provide it, the stub solution doesn't compile with the tests.
* If we don't provide it, the student has to read the test file, find all the possible constructors, and make the `data` type exactly as we want it anyway.

So, I argued to provide it to the student.

We can see that this is distinct from the case where the test demands an abstract type (such as a `Robot`) and wishes to perform some operations on it. In this case:

* the test doesn't care about the implementation of the type
* the student can choose the representation
* therefore we make a `data Robot = Dummy` in the stub file

In this issue I'll discuss a few exercises of the first type:

* allergies: `Allergen`
* meetup: `Weekday` and `Schedule`
* space-age: `Planet`

So, should we give these three exercises the same treatment, and fully define the above-mentioned `data` types, with constructors?

(If doing so, we can remove the `.meta/DONT-TEST-STUB` file for each of these exercises)

**Comment by rbasso** [comment]
I think that this is the way to go. We have to sacrifice a little flexibility in designing exercises, but we gain a more coherent user-experience and automatic testing of stubs. 👍
