### ISSUE TITLE
stubs: Add explicit arguments to functions (good for git practice)

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#473]
As discussed in #459, it seems to be a good idea to add explicit arguments to all the stub solutions, because...

- It complements the type signature, documenting what the arguments are.
- It is easier for beginners that are not yet used to [pointfree style](https://wiki.haskell.org/Pointfree) programming.

For example, in the following code,

```haskell
sayHello :: String -> String
sayHello = error "You need to implement this function."
```

... it is not immediately clear what the argument for the function is. Adding an explicit argument solves the problem:

```haskell
sayHello :: String -> String
sayHello name = "You need to implement this function."
```

Sometimes, the meaning is obvious and generic argument names can be used:

```haskell
concatenate :: [a] -> [a] -> [a]
concatenate xs ys = "You need to implement this function."
```

Considering that this is a great opportunity to expose students to good argument naming practices, we should be extremely careful when choosing the argument names. This is how I usually try to name the arguments:

- First I try to choose a name that help documenting the functions.
- If a more descriptive name is not possible or for some reason undesirable, I use generic argument names, trying to follow what I usually see in the *Prelude*:
  - `x`, `y` and `z` for arguments of the same type.
  - `xs`, `ys` and `zs` for lists and strings.
  - `xss`, `yss`, `zss` for lists of lists.
  - `f`, `g` and `h` for functions.
  - `p` for functions that return a `Bool`.

Below there is a list of exercises that do not have yet explicit arguments in the stubs. The changes are kind of trivial, so this is a good opportunity for anyone trying to get used to `git`:

 - [x] accumulate
 - [x] allergies
 - [x] anagram
 - [x] atbash-cipher
 - [x] bank-account
 - [x] binary-search-tree
 - [x] binary (deprecated)
 - [x] bob
 - [x] bowling
 - [x] clock
 - [x] connect
 - [x] crypto-square
 - [x] custom-set
 - [x] difference-of-squares
 - [x] etl
 - [x] forth
 - [ ] gigasecond (deprecated)
 - [x] go-counting
 - [x] grade-school
 - [x] grains
 - [x] hamming
 - [ ] hexadecimal (deprecated)
 - [x] kindergarten-garden
 - [x] largest-series-product
 - [x] lens-person
 - [x] linked-list
 - [x] list-ops
 - [x] luhn
 - [x] matrix
 - [x] minesweeper
 - [x] nth-prime
 - [x] nucleotide-count
 - [x] ocr-numbers
 - [ ] octal (deprecated)
 - [x] pascals-triangle
 - [x] phone-number
 - [x] pig-latin
 - [x] pov
 - [x] prime-factors
 - [x] pythagorean-triplet
 - [x] queen-attack
 - [x] raindrops
 - [x] rna-transcription
 - [x] robot-name
 - [x] robot-simulator
 - [x] roman-numerals
 - [x] run-length-encoding
 - [x] saddle-points
 - [x] say
 - [x] scrabble-score
 - [x] secret-handshake
 - [x] sgf-parsing
 - [x] sieve
 - [x] simple-cipher
 - [x] simple-linked-list
 - [x] strain
 - [x] sublist
 - [x] sum-of-multiples
 - [x] triangle
 - [ ] trinary (deprecated)
 - [x] wordy
 - [x] zebra-puzzle
 - [x] zipper

Feel free to [open a *pull requests*](https://github.com/exercism/xhaskell#writing-a-pull-request) to fix any exercise in this list, but please use an informative title, like this:

```
exercise-name: Add explicit arguments to the stub functions
```

**Comment by lpalma** [comment]
would you prefer to leave this issue to be gradually solved by newcomers, or would it be ok solve many in a single PR?

**Comment by rbasso** [comment]
At first the idea was to leave it for newcomers but, besides some people I personally asked and oriented, it seems there is no demand for that.

Feel free to solve as many as you want! 👍 

The only thing I think may be a good idea is to make a commit per exercise. What do you think?

**Comment by lpalma** [comment]
yeah a commit per exercise seems the way to go 👍

**Comment by rbasso** [comment]
@petertseng [wrote](https://github.com/exercism/xhaskell/issues/503#issuecomment-285898466):
> Do we want to cover deprecated exercises too as part of #473?

Sorry for that. Sometimes I forget that we have deprecated exercises, because it seems that we cannot remove them from the repository. Feel free to skip or change them, @lpalma!

The list of deprecated exercises is in the `config.json`:
- binary
- gigasecond
- hexadecimal
- octal
- trinary

**Comment by petertseng** [comment]
I have appended "(deprecated)" to those five in the list.
