### ISSUE TITLE
Property-based Testing?

### ISSUE THREAD

**Issue by abo64** [exercism/xhaskell#498]
For some exercises it makes perfect sense to also add some QuickCheck tests.  
A good example would be `simple-linked-list`.

I am aware that this could be quite confusing for people who are unfamiliar with property-based testing.  
And not all languages support it which might be a killer criterion in itself.  
On the other hand the concept could be important enough to expose people to it?

I would like to hear your opinion about this.

**Comment by rbasso** [comment]
I agree that they make sense in Haskell - we even have two exercises that use *QuickCheck* - but I never spent the time to get comfortable enough with it to add new properties. I guess it is time to stop postponing. 😄 

In practice, using property-based testing would makes us diverge at least a little from `x-common` (adding new tests). I don't see any problem in following this route.

In the future, using exclusively property-based tests in some exercise could allow writing less prescriptive test suites, so I support the experiment.

**Comment by abo64** [comment]
Great.
I know Scala's [ScalaCheck](https://www.scalacheck.org/), but I wanted to get into QuickCheck anyways.
So I might just give it a try for `simple-linked-list`.

**Comment by rbasso** [comment]
> Which are those two exercises?

`octal` and `trinary`. Since I know them, they use QuickCheck.

> So I might just give it a try for `simple-linked-list`.

It seems perfect to start with it!

**Comment by petertseng** [comment]
Also don't forget the Diamond exercise, whose readme at https://github.com/exercism/x-common/blob/master/exercises/diamond/description.md has a list of properties that can be used to test. http://blog.ploeh.dk/2015/01/10/diamond-kata-with-fscheck/ has some ideas as well. https://github.com/exercism/x-common/pull/191#issuecomment-254589087 confirms that it would be good to try to test it with property-based tests.

**Comment by petertseng** [comment]
We could also try to retrofit our Dominoes tests at https://github.com/exercism/xhaskell/blob/master/exercises/dominoes/test/Tests.hs#L28 to use QuickCheck?

**Comment by abo64** [comment]
I am sure there are more exercises suitable for property-based testing. My guess would be most of them - if you are just willing to invest enough inventiveness and imagination. :)

One has to be careful, though: Some properties might reveal too much about the solution. Just consider `bob`.

**Comment by petertseng** [comment]
Since this was a question (should we have it) and the question was answered (affirmatively), we are done here, right?

Unless we want to be specific about which exercises it would be good to add QuickCheck to.

**Comment by petertseng** [comment]
Since we don't have diamond, I suppose that suggestion from me doesn't apply. Unless someone adds it to this track. Maybe I'll think about it some day.

Note that https://github.com/exercism/xhaskell/blob/master/exercises/crypto-square/test/Tests.hs also could be a candidate, given what happened in #259 and #391.

**Comment by abo64** [comment]
@rbasso is busy with other things at the moment. So we agreed to just merge #499, but not go any further for now.

**Comment by rbasso** [comment]
Sorry for my absence, @abo64.

I'm trying to force myself to get used property-based tests, but I'm still bad at it and I usually forget about adding tests at all in my toy projects.

To force myself to use them, I even wrote a [stack template](https://raw.githubusercontent.com/rbasso/dotfiles/master/homedir/devel/stack-templates/personal.hsfiles) with a fake test suite... just in case I find the opportunity to practice. 😄
