### ISSUE TITLE
allergies: Test fails but solution works correctly in GHCi

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#505]
### The problem

I just found a comment in [this iteration](http://exercism.io/submissions/ecd23811d84f40f396befa0159b84685) where the user claims that the tests fail, but the program gives the correct results:

> Can anyone explain why I get the "allergies to lots of stuff" test to fail? When I call the function it looks to me the same results as the test case.

In fact, the solution fails the test:

```
Failures:

  test/Tests.hs:71:
  1) allergies.allergies allergic to lots of stuff
```

Here is the content of the failing test:

```haskell
            it "allergic to lots of stuff" $
              allergies 248 `shouldMatch` [ Cats
                                          , Chocolate
                                          , Pollen
                                          , Strawberries
                                          , Tomatoes     ]
```

Surprisingly, this is what I get evaluating `allergies 248` in GHCi, after adding *Show* to `Allergen`:

```
> allergies 248
[Cats,Chocolate,Pollen,Strawberries,Tomatoes]
```

So it seems that the user is right! ✅ 

### Reproducing the problem

Fetch the exercise:

```
exercism fetch haskell allergies
```

Save the following code in `src/Allergies.hs`:

```haskell
module Allergies (Allergen(..), allergies, isAllergicTo) where

import Data.Bits

data Allergen = Eggs
              | Peanuts
              | Shellfish
              | Strawberries
              | Tomatoes
              | Chocolate
              | Pollen
              | Cats
              deriving (Eq, Show)

allergies :: Int -> [Allergen]
allergies x = filter (\allergen -> isAllergicTo allergen x) [ Cats, Chocolate, Eggs, Peanuts, Pollen, Shellfish, Strawberries, Tomatoes]

isAllergicTo :: Allergen -> Int -> Bool
isAllergicTo a x = if (.&.) (allergenAsInt a) x > 0 then True else False

allergenAsInt :: Allergen -> Int
allergenAsInt x = 
  case x of 
    Eggs -> 1
    Peanuts -> 2
    Shellfish -> 4
    Strawberries -> 8
    Tomatoes -> 16
    Chocolate -> 32
    Pollen -> 64
    Cats -> 128
```

Run the test suite:

```
stack test
```

Evaluate `allergies 248` in GHCi:

```
stack repl

> allergen 248
```

Can anyone else reproduce this behavior and maybe also explain why that happens?

---

### What we discovered

The test fails with `-O1`, but not with `-O0`, This may explain why is works in GHCi.

Our best guess is that the optimizer is using a signed 8-bit number when it shouldn't, but we are still trying to isolate the problem in a smaller, reproducible context.

**Comment by abo64** [comment]
`Show` might just be needed for output?

Really strange why this should be required for the test to succeed.
Is this the only test failing?

**Comment by rbasso** [comment]
Just updated it with *Show*. Can you reproduce it, @abo64?

**Comment by abo64** [comment]
Actually no.
`stack test` succeeds for me without `Show`.

**Comment by petertseng** [comment]
both of these fail for me with this solution:

```haskell
it "allergic to cats" $ allergies 128 `shouldMatch` [Cats]
it "has one allergy: cats" $ `shouldBe` 1
```

interesting.

**Comment by petertseng** [comment]
That code was obviously incorrect. OIt hsould be:


```haskell
it "allergic to cats" $ allergies 128 `shouldMatch` [Cats]
it "has one allergy: cats" $ length (allergies 128) `shouldBe` 1
```

**Comment by rbasso** [comment]
For me it fails only the last 3 tests:

```
    allergic to lots of stuff FAILED [1]
    allergic to everything FAILED [2]
    ignore non allergen score parts FAILED [3]
```

But checking the function in GHCi, everything seems correct.

**Comment by rbasso** [comment]
I'm glad you liked the challenge, @petertseng! 😁

**Comment by petertseng** [comment]
Hmm.

Change that `>` to `/=` and the test passes.

Why is that so?

**Comment by rbasso** [comment]
Beats me!

**Comment by petertseng** [comment]
I added a 256, and it doesn't happen to the 256 value. So it's specific to 128.

So, in specific circumstances, 128 is not considered greater than 0?

?__?

**Comment by rbasso** [comment]
I think I found a piece of this puzzle:

Please try to put the following in `package.yaml`:

```
ghc-options: -O0
```

Does it passes the tests?

**Comment by petertseng** [comment]
Yes, test passes with `-O0` for me, even with `>`.

**Comment by rbasso** [comment]
Now the challenge is to find a minimal example where the bug persists. Kind of a bug-coding-golf. 😄

**Comment by NobbZ** [comment]
Decimal 128 is 0x80 in hex, which reinterpreted as signed byte is -1. So something thinks it were clever to use minimal internal memory representation when optimizing. Therefore it is a golden rule of bit wise matching to compare for equality/inequality of a given target value.

**Comment by rbasso** [comment]
Thanks, @NobbZ.
@abo64 also gave me a similar explanation.

The optimizer (`-O1`) is probably representing something as a signed 8-bit integer when it doesn't fit, and this makes `.&.` give unexpected results. Seems consistent with the observed behavior.

It would be useful to isolate that in a minimal reproducible example, so that we could understand better when that happens and maybe file a bug in GHC. Unfortunately, my first attempts at that failed, miserably.

I think it is better to leave this issue open until we are able to isolate the bug. Either finding a ticket that covers this case or filing a bug would allow us to close this issue.

**Comment by petertseng** [comment]
My current smallest reproduction:

```haskell
module Main where

import Data.Bits ((.&.))

data Flag = Bogus1 | Bogus2 | Bogus3 | Flag1 deriving (Eq, Show)

flags :: Int -> [Flag]
flags n = filter (\f -> n .&. (if f == Flag1 then 128 else 1) > 0) [ Flag1, Bogus1, Bogus2, Bogus3 ]

main :: IO ()
main = do
  putStrLn (show (flags 128))
  putStrLn (show ((flags 128) == [Flag1]))
```

please help to improve if you can

**Comment by petertseng** [comment]
Don't need all three bogus flags.

My current smallest reproduction:

```haskell
module Main where

import Data.Bits ((.&.))

data Flag = Bogus | Flag deriving (Eq, Show)

flags :: Int -> [Flag]
flags n = filter (\f -> n .&. (if f == Flag then 128 else 1) > 0) [ Flag, Bogus, Bogus, Bogus ]

main :: IO ()
main = do
  putStrLn (show (flags 128))
  putStrLn (show ((flags 128) == [Flag]))
```

please help to improve if you can

**Comment by petertseng** [comment]
```
$ ghc -O1 f1.hs && ./f1                                       (03-14 03:20)
[1 of 1] Compiling Main             ( f1.hs, f1.o )
Linking f1 ...
[Flag]
False
$ rm f1 f1.hi f1.o                                            (03-14 03:21)
$ ghc -O0 f1.hs && ./f1                                       (03-14 03:21)
[1 of 1] Compiling Main             ( f1.hs, f1.o )
Linking f1 ...
[Flag]
True
```

**Comment by petertseng** [comment]
Fantastic. Don't even need the `data`.

```haskell
module Main where

import Data.Bits ((.&.))

flags :: Int -> [Int]
flags n = filter (\f -> n .&. f > 0) [ 128, 1, 1, 1 ]

main :: IO ()
main = do
  putStrLn (show (flags 128))
  putStrLn (show ((flags 128) == [128]))
```

```
$ ghc -O1 f1.hs && ./f1                                       (03-14 03:31)
[1 of 1] Compiling Main             ( f1.hs, f1.o )
Linking f1 ...
[128]
False
```

**Comment by petertseng** [comment]
You can also `putStrLn (show (length (flags 128)))` to get 0.

**Comment by petertseng** [comment]
It gets better. See the difference between `putStrLn` and `print`.

**Comment by rbasso** [comment]
If you use `(putStrLn . show)` instead of `print` it also returns `[]`.

**Comment by rbasso** [comment]
It seems that this bug is triggered by `-fenable-rewrite-rules`.

**Comment by rbasso** [comment]
```
$ ghc -O1 -fforce-recomp f1.hs; ./f1
[1 of 1] Compiling Main             ( f1.hs, f1.o )
Linking f1 ...
[128]
[]
0
False
```

It seems that disabling rewriting rules, the problem disappears...

```
$ ghc -O1 -fno-enable-rewrite-rules -fforce-recomp f1.hs; ./f1
[1 of 1] Compiling Main             ( f1.hs, f1.o )
Linking f1 ...
[128]
[128]
1
True
```

...but enabling it alone isn't enough to reproduce the problem.

```
$ ghc -O0 -fenable-rewrite-rules -fforce-recomp f1.hs; ./f1
[1 of 1] Compiling Main             ( f1.hs, f1.o )
Linking f1 ...
[128]
[128]
1
True
```

**Comment by rbasso** [comment]
I make some additional test and changed the source a little:

```haskell
import Data.Bits ((.&.))

flags :: Int -> [Int]
flags x = filter (\y -> x .&. y > 0) [1, 128, 129, 255]

main :: IO ()
main = do
  putStrLn $ show $ flags $ 255   -- These lines should display
  putStrLn  (show  (flags   255)) -- the same value, right?

-- It appears that this is related to something that started
-- with GHC 7.10, but was also changed in GHC 8.0, as we can
-- see from the following tests:
--
-- Stack snapshot lts-0.7 (GHC 7.8.3), with -O2
-- [1,128,129,255]
-- [1,128,129,255]
--
-- Stack snapshot lts-2.22 (GHC 7.8.4) with -O2
-- [1,128,129,255]
-- [1,128,129,255]
--
-- Stack snapshot lts-3.22 (GHC 7.10.2) with -O2
-- [1]
-- [1]
--
-- Stack snapshot lts-6.30 (GHC 7.10.3) with -O2
-- [1]
-- [1]
--
-- Stack snapshot lts-7.20 (GHC 8.0.1) with -O2
-- [1]
-- [1,128,129,255]
--
-- Stack snapshot lts-8.5 (GHC 8.0.2) with -O2
-- [1]
-- [1,128,129,255]
--
-- In GHC 8.0, compiling with any of the following...
--   -O0
--   -O2 -fno-cmm-sink
--   -O2 -fno-enable-rewrite-rules
--
-- ...we get the expected results:
-- [1,128,129,255]
-- [1,128,129,255]
--
-- Using only -O1, we get the abnormal behavior again:
-- [1]
-- [1,128,129,255]
```

**Comment by rbasso** [comment]
I just filled [a bug report](https://ghc.haskell.org/trac/ghc/ticket/13425) about it, so I think there is nothing else we can do here.
