### ISSUE TITLE
phone-number: Tests don't seem to match problem description.

### ISSUE THREAD

**Issue by derifatives** [exercism/xhaskell#518]
According to the README file:

The format is usually represented as
```
(NXX)-NXX-XXXX
```
where N is any digit from 2 through 9 and X is any digit from 0 through 9.

This implies that the first digit [and the 4th digit] of the 10 digit number CANNOT be 1, but the tests all use numbers that translate down to 1234567890.

**Comment by rbasso** [comment]
Thanks for opening this issue, @derifatives!

The tests and the the description where recently changed by exercism/x-common#745, but the Haskell track hasn't yet adapted to the new test data.
