### ISSUE TITLE
Zipper: Readme talks about rose trees, tests are for binary trees

### ISSUE THREAD

**Issue by ciderpunx** [exercism/xhaskell#546]
I found it a bit odd that the blurb for the Zipper exercise (http://exercism.io/exercises/haskell/zipper/readme) was about rose trees, but the tests are looking at binary trees (http://exercism.io/exercises/haskell/zipper/test-suite). 

It would be good if the README and the tests matched. I can send a PR to change the README if that helps?

**Comment by rbasso** [comment]
Hi, @ciderpunx!

Thanks for opening this issue.

> It would be good if the README and the tests matched.

Agreed!

> I can send a PR to change the README if that helps?

The `README.md` is dynamically created from a [description.md](https://github.com/exercism/x-common/blob/master/exercises/zipper/description.md) file - shared by all languages in Exercism - and some other language specific files.

The [x-common](https://github.com/exercism/x-common/) repository contains the exercises' shared data, so it would be the correct place to propose this change. Please open an issue there!

**Comment by petertseng** [comment]
Thanks!

Yes, it would be great to open the issue in x-common, and a PR if you could.

**Comment by petertseng** [comment]
Too late. Now it's my turn to ask the question in https://github.com/exercism/problem-specifications/issues/1317.
