### ISSUE TITLE
anagram: Should we case about case sensitivity and/or duplicates?

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#559]
The way the `anagram` exercise is implemented, we demand that the the word comparison is case-insensitive, but we also demand keeping the original word's casing.

Should we lowercase everything before comparing? Is keeping the original word's case part of the exercise?

**Comment by petertseng** [comment]
I guess that is another case of "requirements only implicit in the test cases but not in the README", just like in #547 . It was made this way in https://github.com/exercism/x-common/pull/201

Let's hear a reason to change it

(Otherwise I do not care to change)

**Comment by rbasso** [comment]
Let's leave it the way it is!

If someone complains we can change it later.
