### ISSUE TITLE
nucleotide-count tests don't enforce valid strand constraint

### ISSUE THREAD

**Issue by mambocab** [exercism/xhaskell#58]
In [the tests for nucleotide-count](https://github.com/exercism/xhaskell/blob/master/nucleotide-count/nucleotide-count_test.hs), this test case:

```haskell
assertError "invalid nucleotide 'X'" $ count 'X' "GACT"
```

ensures that the implementation checks that the nucleotide being counted is valid. However, there is no such test for the strand whose nucleotides are being counted, for `count` or `nucleotideCounts`.

The [example implementation](https://github.com/exercism/xhaskell/blob/master/nucleotide-count/example.hs) does check for this, so I thought it might be a missing test case.

**Comment by etrepum** [comment]
Sounds like a reasonable thing to do, want to submit a pull request?

**Comment by mambocab** [comment]
Happy to.
