### ISSUE TITLE
Binary search tree cannot be a monoid

### ISSUE THREAD

**Issue by sjakobi** [exercism/xhaskell#59]
I was surprised that the binary-search-tree exercise doesn't allow solutions where the BST can be empty. 

The problem is that the `bstValue` function is of type `BST a -> a` instead of of `BST a -> Maybe a`.
This also means that the `fromList` function must have a special case where it returns an error for the empty list.

In the example solution the BST is defined as:
```haskell
data BST a = Node { bstValue :: a
                  , bstLeft :: Maybe (BST a)
                  , bstRight :: Maybe (BST a) }
```
Wouldn't a definition like the following be nicer?

```haskell
data BST a = Tip
           | Node (BST a) a (BST a)
```

**Comment by etrepum** [comment]
That would be reasonable if `bstValue` was `BST a -> Maybe a`
