### ISSUE TITLE
gigasecond: use times (not dates) for inputs and outputs

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xhaskell#63]
A duration of a gigasecond should be measured in seconds, not
days.

The `gigasecond` problem has been implemented in a number of languages,
and this issue has been generated for each of these language tracks.
This may already be fixed in this track, if so, please make a note of it
and close the issue.

There has been some discussion about whether or not gigaseconds should
take daylight savings time into account, and the conclusion was "no", since
not all locations observe daylight savings time.

**Comment by etrepum** [comment]
With regard to daylight savings, if you're using a standard library it will almost certainly take daylight savings into account for you. This could make it hard to write the tests properly unless you normalize the test datetimes to UTC or build them from epoch seconds (which would reveal a very obvious way to solve the problem).

**Comment by kytrinyx** [comment]
In that case I suggest that let the daylight savings stuff as is.
