### ISSUE TITLE
meetup, what does "-teenth" mean?

### ISSUE THREAD

**Issue by NobbZ** [exercism/xhaskell#66]
Hi there!

I can't make any sense from the "-teenth" stuff mentioned in the exercise… Perhaps someone could clarify what it means?

Sidenote: Also various translators did not know the term "monteenth" or similar…

**Comment by kytrinyx** [comment]
It's a made-up term, I'll add some clarification.

**Comment by kytrinyx** [comment]
Updated in exercism/x-common@306c038fcabe3f7c75e4dd7f0684493096301da2

Sorry about the confusion!

**Comment by cprieto** [comment]
I feel sorry to awake this old issue but honestly, I had checked all the answers and they look more like brute force to me to make the test happy.

Yes, I read the new clarification of "a meetup realised... yada yada" but what about that? that basically said absolutely nothing useful to fix or do the test?

Would be nice to add more explanation, especially for non-English speakers or mind readers, something like:

"When we define -teeth it means that it is the day when the moon rises in the horizon for that given month" or something more descriptive.
