### ISSUE TITLE
Add helpful information to the SETUP.md

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xhaskell#68]
The contents of the SETUP.md file gets included in
the README.md that gets delivered when a user runs the `exercism fetch`
command from their terminal.

At the very minimum, it should contain a link to the relevant
language-specific documentation on
[help.exercism.io](http://help.exercism.io).

It would also be useful to explain in a generic way how to run the tests.
Remember that this file will be included with _all_ the problems, so it gets
confusing if we refer to specific problems or files.

Some languages have very particular needs in terms of the solution: nested
directories, specific files, etc. If this is the case here, then it would be
useful to explain what is expected.

------

Thanks, @tejasbubane for suggesting that we add this documentation everywhere.
See [exercism.io#2198](https://github.com/exercism/exercism.io/issues/2198).

**Comment by wachr** [comment]
Hi @kytrinyx, I just created a pull request for a patch for this. I'm pretty new to Github so apologies if I overlooked some convention or contributing rules. I'd really like to participate in something on Gtihub and I've very much enjoyed Exercism so any feedback or criticism is welcome and I will try to respond promptly.

**Comment by etrepum** [comment]
Thanks @wachr!

**Comment by kytrinyx** [comment]
This looks great, thanks!
