### ISSUE TITLE
Meetup - 5th Monday

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xhaskell#69]
There is an interesting edge case in the meetup problem:
some months have five Mondays.

March of 2015 has five Mondays (the fifth being March 30th), whereas
February of 2015 does not, and so should produce an error.

------

Thanks, @JKesMc9tqIQe9M for pointing out the edge case.
See [exercism.io#2142](https://github.com/exercism/exercism.io/issues/2142).

**Comment by etrepum** [comment]
I'm going to close this because it doesn't make sense to schedule a monthly meetup on the fifth week. It's not possible to schedule a meetup that would fail on some months (with the current types), which seems like the right design for this particular problem.

**Comment by kytrinyx** [comment]
That's a good point. This would be a "once in a blue moon" type of meetup, which is pretty difficult to manage.
