### ISSUE TITLE
QuickCheck?

### ISSUE THREAD

**Issue by joneshf** [exercism/xhaskell#71]
It seems that only two tests are using QC right now: https://github.com/exercism/xhaskell/blob/d238a331c2bccaa1d86522198e0a85235a6356d6/octal/octal_test.hs and https://github.com/exercism/xhaskell/blob/d238a331c2bccaa1d86522198e0a85235a6356d6/trinary/trinary_test.hs.

However, I'd think that almost all of the tests should use QC. Any reason why they aren't? Up for PR's?

I'm not implying that HUnit should be replaced entirely, but I think QC should be able to take care of most of the testing. HUnit can still be used for specific test cases.

**Comment by etrepum** [comment]
The tests are mostly ported from other languages, no reason why we wouldn't accept pull requests to add better tests. One issue is that QC tests may reveal a bit too much about the solution in exercises that don't forbid the usage of some libraries.
