### ISSUE TITLE
Add type information.

### ISSUE THREAD

**Issue by joneshf** [exercism/xhaskell#72]
It'd be immensely helpful to add the types for the required functions. Maybe this can come in an additional markdown file? Or maybe just a blurb in the tests. Currently I'm having to glean the type information from the tests, that seems like the wrong way.

**Comment by etrepum** [comment]
In some cases there's a bit of flexibility to what types you can use for a given exercise, and part of the challenge is coming up with the right types. I could go either way on this. If you don't provide types, or use typed holes, then the compiler will tell you what the necessary types are.

**Comment by joneshf** [comment]
Yeah, I can see both sides. But I think it's way more instructive to not have to struggle though the types. Ideally you'd not have to look at the test file at all to see what types are necessary. 

Maybe this could happen piecemeal. For exercises where the type is part of the goal, don't provide an explicit type signature. But for ones where the type is largely irrelevant to the exercise, no need in struggling with that as well.

**Comment by etrepum** [comment]
I'll leave that up to your discretion, please feel free to submit pull requests to add comments and/or stub files for exercises where you think this would be most helpful. I'll close this issue and those can be handled on a case by case basis.

In many cases the types are opaque to the tests, and it's better to leave the actual definition of the type to the discretion of the person completing the exercise. There are often many valid ways to define a type, and even when only one type truly makes sense there's plenty that can be learned from by going down the wrong path.
