### ISSUE TITLE
Gigasecond - Could not find module ‘System.Locale’

### ISSUE THREAD

**Issue by topher6345** [exercism/xhaskell#85]
I'm a newb to Haskell and I'm doing the Gigasecond exercise in Haskel. I'm getting this error - 

when I run `runhaskell -Wall gigasecond_test.hs`

```
gigasecond_test.hs:7:8:
    Could not find module ‘System.Locale’
```

```
Glasgow Haskell Compiler, Version 7.10.1, stage 2 booted by GHC version 7.10.1
Using binary package database: /usr/local/Cellar/ghc/7.10.1_1/lib/ghc-7.10.1/package.conf.d/package.cache
Using binary package database: ~/.ghc/x86_64-darwin-7.10.1/package.conf.d/package.cache
wired-in package ghc-prim mapped to ghc-prim-0.4.0.0-7c945cc0c41d3b7b70f3edd125671166
wired-in package integer-gmp mapped to integer-gmp-1.0.0.0-3c947e5fb6dca14804d9b2793c521b67
wired-in package base mapped to base-4.8.0.0-9015e10d2b2b0f71f570c3f2bbe09c8a
wired-in package rts mapped to builtin_rts
wired-in package template-haskell mapped to template-haskell-2.10.0.0-7dd4b8bf14d5c74339cc9bf2cb38ffa4
wired-in package ghc mapped to ghc-7.10.1-5786533e1406205cf5a1af1a23ee7528
wired-in package dph-seq not found.
wired-in package dph-par not found.
```

I ran`cabal install system`and it  returned `cabal: There is no package named 'system'.`

Is this an error on my end?

**Comment by hojgr** [comment]
Just run into the same issue. Have you found any solution to this?

**Comment by topher6345** [comment]
No I still haven't

**Comment by hojgr** [comment]
I managed to solve it yesterday by installing package `old-time`
`cabal install old-time`

**Comment by hojgr** [comment]
I am just learning haskell, but wouldnt it just be better to use a time library included with Haskell Platform by default? The `old-time` seems to be deprecated (it has `old` in it :) )

**Comment by kytrinyx** [comment]
That sounds reasonable, I just don't know if there's some other intended approach to all of this.

**Comment by NobbZ** [comment]
The interface used in the tests, has been around in Plattform quite a long time, at least a decade. This was also current when the track got its last update to a current version of Plattform/GHC.

I don't know why it has been removed or deprecated from Plattform last year, but I do see, that xhaskells maintainers are very silent.

Perhaps someone with enough knowledge and time can take the track over?

**Comment by kytrinyx** [comment]
> Perhaps someone with enough knowledge and time can take the track over?

Yes, that would be excellent. I'll reach out to some folks over the next few weeks.

**Comment by hbarney** [comment]
I made the test file compile by removing the import for `System.Locale` and adding `iso8601DateFormat` to the import for `Data.Time.Format`.
`import Data.Time.Format (TimeLocale, ParseTime, parseTimeOrError, defaultTimeLocale, iso8601DateFormat)`

It seems to work fine then.

**Comment by daniloisr** [comment]
Thanks @hbarney! Your tip worked for me:

> I made the test file compile by removing the import for System.Locale and adding iso8601DateFormat to the import for Data.Time.Format.

I also opened a PR fixing this https://github.com/exercism/xhaskell/pull/96

@etrepum can you take a look? :smile:

**Comment by kytrinyx** [comment]
I went ahead and merged it. If there's a better approach, let's discuss!
