### ISSUE TITLE
triangle: incorrect test in some tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xhaskell#91]
Please check if there's a test that states that a triangle with sides 2, 4, 2 is invalid. The triangle inequality states that for any triangle, the sum of the lengths of any two sides must be greater than or equal to the length of the remaining side. If this doesn't affect this track, go ahead and just close the issue.

**Comment by NobbZ** [comment]
There is no 2, 2, 4 but the very similar 1, 1, 2. The tests demand this to be of kind `Illogical`.

**Comment by kytrinyx** [comment]
Let's wait for the discussion here to settle: https://github.com/exercism/xerlang/issues/85 then deal with this in all the tracks a week or so from now.

**Comment by kytrinyx** [comment]
There was a bit of confusion with this issue. I've summarized my current understanding here: https://github.com/exercism/x-common/issues/202

I am closing this issue. If necessary I will open a new issue once we have come to an agreement about how to resolve the inconsistencies and what exact steps to take.
