### ISSUE TITLE
pov: Consider making tests insensitive to child ordering

### ISSUE THREAD

**Issue by petertseng** [exercism/xhaskell#92]
In the [pov tests](https://github.com/exercism/xhaskell/blob/master/pov/pov_test.hs), given a tree that must be reparented on node `x`, the tests ensure that the former parent of `x` comes *after* the former children of `x`.

I think it would be beneficial if the tests did not care about the ordering of the children, since trees probably don't care about the ordering of their children, and it almost certainly is valid to allow either order in the POV problem.

**Comment by kytrinyx** [comment]
Yeah, allowing either ordering would be great.

**Comment by petertseng** [comment]
Surveying the other languages that implement this exercise.

* [xgo](https://github.com/exercism/xgo/blob/master/exercises/pov/pov_test.go) allows any ordering because it only checks for the presence of edges, and sorts the edges before checking presence.
* [xclojure](https://github.com/exercism/xclojure/blob/master/exercises/pov/test/pov_test.clj) seems to also be sensitive to ordering; IIRC clojure vectors (denoted by `[]`) only compare equal if the elements are in the same order. Though I will note that Clojure, in expecting the former parent comes *after* the former children in a vector, expresses an ordering that is more likely to be the default choice, since `conj` onto a vector appends onto the end of the vector. Nevertheless, it could be worth filing an issue for them as well.

**Comment by petertseng** [comment]
Expanding more on the work required for this track:

This matters when we are reparenting a node that has *both* a parent and some children. That means the "reparenting kids" and "reparenting cousins" test cases.
